package com.pathways.beyond.client.model;

/**
 * Boss skin UV layouts, in texture pixels. GENERATED by tools/gen_entities.py -
 * do not hand-edit. Each entry is {{u, v}, {{w, h, d}}} for a box-UV unfolded cube,
 * exactly as vanilla unfolds skins: top, bottom, right, front, left, back.
 */
public final class BossLayout {
    private BossLayout() {}

    /** Choirmaster sheet: 128x128. */
    public static final int[][] CHOIRMASTER = {
            // head
            {0, 0, 12, 12, 12},
            // mitre
            {48, 0, 14, 10, 14},
            // body
            {0, 32, 16, 24, 8},
            // right_arm
            {56, 0, 8, 24, 8},
            // left_arm
            {88, 0, 8, 24, 8},
            // right_leg
            {0, 64, 8, 24, 8},
            // left_leg
            {32, 64, 8, 24, 8},
            // book
            {64, 64, 10, 14, 2},
    };

    /** The Unblinking sheet: 128x128 (eyeball 64x48x64, iris disc, lid plate). */
    public static final int[][] UNBLINKING = {
            // eyeball
            {0, 0, 64, 48, 64},
            // iris
            {0, 52, 32, 32, 2},
            // lid
            {96, 0, 64, 16, 64},
    };

    /** Index into the layout arrays. */
    public static final int CHOIRMASTER_HEAD = 0;
    public static final int CHOIRMASTER_MITRE = 1;
    public static final int CHOIRMASTER_BODY = 2;
    public static final int CHOIRMASTER_RIGHT_ARM = 3;
    public static final int CHOIRMASTER_LEFT_ARM = 4;
    public static final int CHOIRMASTER_RIGHT_LEG = 5;
    public static final int CHOIRMASTER_LEFT_LEG = 6;
    public static final int CHOIRMASTER_BOOK = 7;
}
