// GENERATED by tools/gen_java_registries.py from tools/content.py - do not hand-edit.

package com.pathways.beyond.pathway;

import java.util.List;
import java.util.Map;

/**
 * All pathway / sequence definitions. The Fool pathway is implemented to Sequence 0;
 * the other seven are registered with their sequence ladders and potions so they can be
 * developed without touching the registry.
 */
public final class PathwayData {
    private PathwayData() {}

    /** One sequence: its index (9 = weakest, 0 = strongest), name, lore and abilities. */
    public record SequenceDef(int sequence, String id, String name, String lore,
                              List<String> abilities, String potionId) {}

    /** One pathway: identity, colour language, lore and the ten sequences. */
    public record PathwayDef(String id, String displayName, int colour, int accent,
                             String emblem, int deepestImplemented, String lore,
                             List<SequenceDef> sequences) {
        public SequenceDef bySequence(int seq) {
            for (SequenceDef s : sequences) {
                if (s.sequence() == seq) return s;
            }
            return null;
        }
        public int maxSequence() { return deepestImplemented; }
    }

    // ---- ability ids per sequence (implemented in Abilities.java) ----
    private static final Map<String, List<String>> ABILITIES_FOOL = Map.ofEntries(
            Map.entry("seer", List.of("supernatural_sight", "ore_sense", "danger_premonition", "perception")),
            Map.entry("clown", List.of("unnatural_agility", "fold_step", "dodge_instinct", "combat_prediction")),
            Map.entry("magician", List.of("stage_illusion", "blink", "decoy_double", "perception_rewrite")),
            Map.entry("faceless", List.of("wear_face", "borrowed_mien", "feature_shift", "mask_of_nobody")),
            Map.entry("marionettist", List.of("soul_thread_view", "bind_puppet", "puppet_command", "sever_thread")),
            Map.entry("bizarro_sorcerer", List.of("bizarro_copy", "reality_warp", "twisted_mirage", "argument_of_copies")),
            Map.entry("scholar_of_yore", List.of("read_the_stone", "memory_echo_runtime", "echo_summon", "rewind_moment")),
            Map.entry("miracle_invoker", List.of("small_miracle", "wish_lantern", "rainstorm_of_quiet", "debt_of_miracles")),
            Map.entry("attendant_of_mysteries", List.of("forbidden_ward", "deep_ritual", "astral_walk", "authority_to_forbid")),
            Map.entry("the_fool", List.of("between_two_truths", "unreality_walk", "the_space_between", "the_noticing_dawn"))
    );

    private static final Map<String, List<String>> ABILITIES_SUN = Map.ofEntries(Map.entry("bard", PLACEHOLDER), Map.entry("light_supplicant", PLACEHOLDER), Map.entry("solar_high_priest", PLACEHOLDER), Map.entry("notary", PLACEHOLDER), Map.entry("priest_of_light", PLACEHOLDER), Map.entry("unshadowed", PLACEHOLDER), Map.entry("justice_knight", PLACEHOLDER), Map.entry("sun_priest", PLACEHOLDER), Map.entry("sun", PLACEHOLDER), Map.entry("sun_god", PLACEHOLDER));
    private static final Map<String, List<String>> ABILITIES_DEATH = Map.ofEntries(Map.entry("corpse_collector", PLACEHOLDER), Map.entry("gravedigger", PLACEHOLDER), Map.entry("spirit_medium", PLACEHOLDER), Map.entry("undertaker", PLACEHOLDER), Map.entry("gatekeeper", PLACEHOLDER), Map.entry("carrion_king", PLACEHOLDER), Map.entry("pale_rider", PLACEHOLDER), Map.entry("death_priest", PLACEHOLDER), Map.entry("death", PLACEHOLDER), Map.entry("pale_crown", PLACEHOLDER));
    private static final Map<String, List<String>> ABILITIES_DOOR = Map.ofEntries(Map.entry("apprentice", PLACEHOLDER), Map.entry("traveller", PLACEHOLDER), Map.entry("sleight_of_hand", PLACEHOLDER), Map.entry("dimensional_walker", PLACEHOLDER), Map.entry("sealing_master", PLACEHOLDER), Map.entry("gate", PLACEHOLDER), Map.entry("key_of_doors", PLACEHOLDER), Map.entry("doors_end", PLACEHOLDER), Map.entry("door", PLACEHOLDER), Map.entry("the_hinge", PLACEHOLDER));
    private static final Map<String, List<String>> ABILITIES_VISIONARY = Map.ofEntries(Map.entry("spectator", PLACEHOLDER), Map.entry("telepathist", PLACEHOLDER), Map.entry("psychiatrist", PLACEHOLDER), Map.entry("dream_walker", PLACEHOLDER), Map.entry("illusionist", PLACEHOLDER), Map.entry("nighmare_lord", PLACEHOLDER), Map.entry("mind_city", PLACEHOLDER), Map.entry("collective_voice", PLACEHOLDER), Map.entry("visionary", PLACEHOLDER), Map.entry("dream_world", PLACEHOLDER));
    private static final Map<String, List<String>> ABILITIES_BLACK_EMPEROR = Map.ofEntries(Map.entry("lawyer", PLACEHOLDER), Map.entry("briber", PLACEHOLDER), Map.entry("mentor", PLACEHOLDER), Map.entry("inventor", PLACEHOLDER), Map.entry("director", PLACEHOLDER), Map.entry("politician", PLACEHOLDER), Map.entry("order_maker", PLACEHOLDER), Map.entry("black_emperor_candidate", PLACEHOLDER), Map.entry("black_emperor", PLACEHOLDER), Map.entry("iron_throne", PLACEHOLDER));
    private static final Map<String, List<String>> ABILITIES_ERROR = Map.ofEntries(Map.entry("marauder", PLACEHOLDER), Map.entry("swindler", PLACEHOLDER), Map.entry("assassin", PLACEHOLDER), Map.entry("corruption_dealer", PLACEHOLDER), Map.entry("thief_of_bodies", PLACEHOLDER), Map.entry("shadow_of_the_veil", PLACEHOLDER), Map.entry("grand_thief", PLACEHOLDER), Map.entry("conceptual_marauder", PLACEHOLDER), Map.entry("error", PLACEHOLDER), Map.entry("the_mistake", PLACEHOLDER));
    private static final Map<String, List<String>> ABILITIES_MOTHER = Map.ofEntries(Map.entry("planter", PLACEHOLDER), Map.entry("harvester", PLACEHOLDER), Map.entry("beast_tamer", PLACEHOLDER), Map.entry("herbalist", PLACEHOLDER), Map.entry("florist", PLACEHOLDER), Map.entry("mother_of_maggots", PLACEHOLDER), Map.entry("blight_bringer", PLACEHOLDER), Map.entry("green_hand", PLACEHOLDER), Map.entry("mother", PLACEHOLDER), Map.entry("the_fertile_void", PLACEHOLDER));

    public static final List<PathwayDef> ALL = List.of(
            // ---- The Fool ----
            new PathwayDef(
                    "fool", "The Fool", 0xFF7B5AA0, 0xFFB49BD0,
                    "the_fool", 0,
                    "Not a god of trickery but of the space between: the Fool is the pathway of those who are not there, of masks worn so long they grow a face. Its church teaches that reality is a negotiation, and that the Fool is the only honest deity, because it never claims to be real.",
                    List.of(
                new SequenceDef(9, "seer", "Seer", "Perceive what should not be perceived: auras, hidden veins of ore, the shape of approaching danger, and the presence of things that have no shadow.", ABILITIES_FOOL.get("seer"), "potion_seer"),
                new SequenceDef(8, "clown", "Clown", "The body becomes a joke told to physics. Folding steps, dodging before the blow exists, and reading an opponent's intent in their posture.", ABILITIES_FOOL.get("clown"), "potion_clown"),
                new SequenceDef(7, "magician", "Magician", "Misdirection made literal: short blinks through space, decoys that bleed when struck, and perception rewritten for a few seconds.", ABILITIES_FOOL.get("magician"), "potion_magician"),
                new SequenceDef(6, "faceless", "Faceless", "Wear a face like a glove. Mimic the gait, voice and outline of anything humanoid, and let your own features rest somewhere else.", ABILITIES_FOOL.get("faceless"), "potion_faceless"),
                new SequenceDef(5, "marionettist", "Marionettist", "The Soul Thread becomes a leash. Bind the living to your fingers and make puppets of those who still believe they are free.", ABILITIES_FOOL.get("marionettist"), "potion_marionettist"),
                new SequenceDef(4, "bizarro_sorcerer", "Bizarro Sorcerer", "Copies that argue with the original. Local reality distortion, mirrored terrain, and illusions that keep moving after you stop concentrating.", ABILITIES_FOOL.get("bizarro_sorcerer"), "potion_bizarro_sorcerer"),
                new SequenceDef(3, "scholar_of_yore", "Scholar of Yore", "Read a place like a page: the memory of stone, the echoes of what was said here, and the shaping of what nearly happened.", ABILITIES_FOOL.get("scholar_of_yore"), "potion_scholar"),
                new SequenceDef(2, "miracle_invoker", "Miracle Invoker", "Small violations of cause and effect, granted as favours. Each miracle is answered by something, and that something keeps a ledger.", ABILITIES_FOOL.get("miracle_invoker"), "potion_miracle_invoker"),
                new SequenceDef(1, "attendant_of_mysteries", "Attendant of Mysteries", "You are no longer a person who knows secrets; you are the room the secrets are kept in. Spirit projection, advanced ritual, and the authority to forbid.", ABILITIES_FOOL.get("attendant_of_mysteries"), "potion_attendant"),
                new SequenceDef(0, "the_fool", "The Fool", "You become the space between two truths. Perception, distance and causality become matters of taste. Nothing about you is human any more, and the world has begun to notice.", ABILITIES_FOOL.get("the_fool"), "potion_the_fool")
                    )),
            // ---- The Sun ----
            new PathwayDef(
                    "sun", "The Sun", 0xFFD4B265, 0xFFEBD08A,
                    "the_sun", 9,
                    "Light that burns what it blesses. The Sun's priests are healers and executioners in the same vestment, and its higher sequences are remembered mostly as brightness and then as absence.",
                    List.of(
                new SequenceDef(9, "bard", "Bard", "Voice, story and courage: bolster allies, and be believed.", ABILITIES_SUN.get("bard"), "potion_bard"),
                new SequenceDef(8, "light_supplicant", "Light Supplicant", "Channels daylight into small blessings and into burns.", ABILITIES_SUN.get("light_supplicant"), null),
                new SequenceDef(7, "solar_high_priest", "Solar High Priest", "Sanctifies ground; unholy things refuse to stand there.", ABILITIES_SUN.get("solar_high_priest"), null),
                new SequenceDef(6, "notary", "Notary", "Binds agreements with real power: an oath broken costs the oathbreaker.", ABILITIES_SUN.get("notary"), null),
                new SequenceDef(5, "priest_of_light", "Priest of Light", "Judgement made visible; wounds close as sins are named.", ABILITIES_SUN.get("priest_of_light"), null),
                new SequenceDef(4, "unshadowed", "Unshadowed", "Casts no shadow, suffers no darkness; light calls you home.", ABILITIES_SUN.get("unshadowed"), null),
                new SequenceDef(3, "justice_knight", "Knight of Justice", "Armour of conviction, sword of verdict.", ABILITIES_SUN.get("justice_knight"), null),
                new SequenceDef(2, "sun_priest", "Sun Priest", "A walking noon; lesser supernatural things simply cease.", ABILITIES_SUN.get("sun_priest"), null),
                new SequenceDef(1, "sun", "The Sun", "You are a small, terrible daylight. Do not look at me.", ABILITIES_SUN.get("sun"), null),
                new SequenceDef(0, "sun_god", "The Blazing Sun", "The throne of the Sun is not a seat. It is an orbit.", ABILITIES_SUN.get("sun_god"), null)
                    )),
            // ---- Death ----
            new PathwayDef(
                    "death", "Death", 0xFF4C6749, 0xFF6F8A63,
                    "death", 9,
                    "The pathway keeps a ledger of everything that has stopped. Its believers are not morbid; they are administrative. Nothing is lost, only filed.",
                    List.of(
                new SequenceDef(9, "corpse_collector", "Corpse Collector", "Speaks with the recently dead and keeps what they no longer need.", ABILITIES_DEATH.get("corpse_collector"), "potion_corpse_collector"),
                new SequenceDef(8, "gravedigger", "Gravedigger", "Ground that accepts everything; summons the buried to hold you.", ABILITIES_DEATH.get("gravedigger"), "potion_gravedigger"),
                new SequenceDef(7, "spirit_medium", "Spirit Medium", "Opens a door for the dead and closes it on time.", ABILITIES_DEATH.get("spirit_medium"), null),
                new SequenceDef(6, "undertaker", "Undertaker", "Prepares vessels: curses travel, possessions break.", ABILITIES_DEATH.get("undertaker"), null),
                new SequenceDef(5, "gatekeeper", "Gatekeeper", "Decides what may cross, and what may not come back.", ABILITIES_DEATH.get("gatekeeper"), null),
                new SequenceDef(4, "carrion_king", "Carrion King", "Death feeds you; wounds rot shut.", ABILITIES_DEATH.get("carrion_king"), null),
                new SequenceDef(3, "pale_rider", "Pale Rider", "Your passage ages the living and gentles the dying.", ABILITIES_DEATH.get("pale_rider"), null),
                new SequenceDef(2, "death_priest", "Death Priest", "Perform the last rite on anything, including the immortal.", ABILITIES_DEATH.get("death_priest"), null),
                new SequenceDef(1, "death", "Death", "Not a killer - a conclusion. You may end a thing completely.", ABILITIES_DEATH.get("death"), null),
                new SequenceDef(0, "pale_crown", "The Pale Crown", "Everything that lives feels the ledger shift when you move.", ABILITIES_DEATH.get("pale_crown"), null)
                    )),
            // ---- The Door ----
            new PathwayDef(
                    "door", "The Door", 0xFF3A6C96, 0xFF63A2B8,
                    "the_door", 9,
                    "Space is a corridor with too many hinges. The Door's adepts do not travel; they arrive, and they seal behind themselves in ways that should not hold.",
                    List.of(
                new SequenceDef(9, "apprentice", "Apprentice", "Learn any trade impossibly fast; your hands remember what you never practised.", ABILITIES_DOOR.get("apprentice"), "potion_apprentice"),
                new SequenceDef(8, "traveller", "Traveller", "Short steps that cross long distances.", ABILITIES_DOOR.get("traveller"), null),
                new SequenceDef(7, "sleight_of_hand", "Sleight of Hand", "Steal from anywhere: pockets, vaults, memories.", ABILITIES_DOOR.get("sleight_of_hand"), null),
                new SequenceDef(6, "dimensional_walker", "Dimensional Walker", "Step sideways into the Spirit World at will.", ABILITIES_DOOR.get("dimensional_walker"), null),
                new SequenceDef(5, "sealing_master", "Sealing Master", "A room that cannot be entered, a door that cannot be found.", ABILITIES_DOOR.get("sealing_master"), null),
                new SequenceDef(4, "gate", "Gate", "You are a threshold. What passes through you is changed.", ABILITIES_DOOR.get("gate"), null),
                new SequenceDef(3, "key_of_doors", "Key of Doors", "Convince any locked thing that it was never locked.", ABILITIES_DOOR.get("key_of_doors"), null),
                new SequenceDef(2, "doors_end", "End of Doors", "Remove the concept of 'here' from a place.", ABILITIES_DOOR.get("doors_end"), null),
                new SequenceDef(1, "door", "The Door", "Standing open is the most dangerous thing a god can do.", ABILITIES_DOOR.get("door"), null),
                new SequenceDef(0, "the_hinge", "The Hinge", "Father of keys, mother of corridors; both sides obey.", ABILITIES_DOOR.get("the_hinge"), null)
                    )),
            // ---- The Visionary ----
            new PathwayDef(
                    "visionary", "The Visionary", 0xFF63A2B8, 0xFFA8DCE2,
                    "visionary", 9,
                    "The mind is the largest country. Visionaries map it, tax it, and occasionally declare war on a thought until it apologises.",
                    List.of(
                new SequenceDef(9, "spectator", "Spectator", "Watch a mind and see its weather.", ABILITIES_VISIONARY.get("spectator"), "potion_spectator"),
                new SequenceDef(8, "telepathist", "Telepathist", "Read intent before language forms.", ABILITIES_VISIONARY.get("telepathist"), null),
                new SequenceDef(7, "psychiatrist", "Psychiatrist", "Enter a mind, tidy it, leave a door open.", ABILITIES_VISIONARY.get("psychiatrist"), null),
                new SequenceDef(6, "dream_walker", "Dream Walker", "Work in sleep; kill in sleep.", ABILITIES_VISIONARY.get("dream_walker"), null),
                new SequenceDef(5, "illusionist", "Illusionist", "A crowd believes your lie so hard it becomes architecture.", ABILITIES_VISIONARY.get("illusionist"), null),
                new SequenceDef(4, "nighmare_lord", "Nightmare Lord", "Fear is a currency and you are the mint.", ABILITIES_VISIONARY.get("nighmare_lord"), null),
                new SequenceDef(3, "mind_city", "City of the Mind", "You keep a city inside your skull and it is populated.", ABILITIES_VISIONARY.get("mind_city"), null),
                new SequenceDef(2, "collective_voice", "Collective Voice", "Every mind in earshot speaks with your accent.", ABILITIES_VISIONARY.get("collective_voice"), null),
                new SequenceDef(1, "visionary", "The Visionary", "You have seen the end of thought and did not look away.", ABILITIES_VISIONARY.get("visionary"), null),
                new SequenceDef(0, "dream_world", "The Dreaming World", "Waking is now the smaller of your two lives.", ABILITIES_VISIONARY.get("dream_world"), null)
                    )),
            // ---- Black Emperor ----
            new PathwayDef(
                    "black_emperor", "Black Emperor", 0xFF9C7C3A, 0xFFD4B265,
                    "black_emperor", 9,
                    "Empire is a ritual performed continuously. Its adepts do not command people; they command the arrangements that make people behave.",
                    List.of(
                new SequenceDef(9, "lawyer", "Lawyer", "Find the clause reality forgot, and use it.", ABILITIES_BLACK_EMPEROR.get("lawyer"), "potion_lawyer"),
                new SequenceDef(8, "briber", "Briber", "Every price is payable; you always find the coin.", ABILITIES_BLACK_EMPEROR.get("briber"), null),
                new SequenceDef(7, "mentor", "Mentor", "Your students carry your authority into rooms you never enter.", ABILITIES_BLACK_EMPEROR.get("mentor"), null),
                new SequenceDef(6, "inventor", "Inventor", "Build the instrument that makes your claim true.", ABILITIES_BLACK_EMPEROR.get("inventor"), null),
                new SequenceDef(5, "director", "Director", "Cast the world: roles, props, and a script nobody read.", ABILITIES_BLACK_EMPEROR.get("director"), null),
                new SequenceDef(4, "politician", "Politician", "Two lies and a compromise; you profit from all three.", ABILITIES_BLACK_EMPEROR.get("politician"), null),
                new SequenceDef(3, "order_maker", "Order Maker", "Write a rule into the local fabric of cause and effect.", ABILITIES_BLACK_EMPEROR.get("order_maker"), null),
                new SequenceDef(2, "black_emperor_candidate", "Emperor Candidate", "An army follows you because it is elegant.", ABILITIES_BLACK_EMPEROR.get("black_emperor_candidate"), null),
                new SequenceDef(1, "black_emperor", "Black Emperor", "You rule by being the thing everyone is arranged around.", ABILITIES_BLACK_EMPEROR.get("black_emperor"), null),
                new SequenceDef(0, "iron_throne", "The Iron Throne", "Not a seat: an organising principle of the world.", ABILITIES_BLACK_EMPEROR.get("iron_throne"), null)
                    )),
            // ---- Error ----
            new PathwayDef(
                    "error", "Error", 0xFF0E0C10, 0xFFB03A34,
                    "error", 9,
                    "A flaw that propagates. The Error pathway has no doctrine, because doctrine is something it can corrupt and it would rather keep its options open.",
                    List.of(
                new SequenceDef(9, "marauder", "Marauder", "Take what was not yours; leave a copy that rots.", ABILITIES_ERROR.get("marauder"), "potion_marauder"),
                new SequenceDef(8, "swindler", "Swindler", "An honest face and a ledger written in someone else's hand.", ABILITIES_ERROR.get("swindler"), null),
                new SequenceDef(7, "assassin", "Assassin", "One movement, no witness, no sound but the after-image.", ABILITIES_ERROR.get("assassin"), null),
                new SequenceDef(6, "corruption_dealer", "Corruption Dealer", "Trade in what makes people less than they were.", ABILITIES_ERROR.get("corruption_dealer"), null),
                new SequenceDef(5, "thief_of_bodies", "Thief of Bodies", "Borrow a body; return it wrong.", ABILITIES_ERROR.get("thief_of_bodies"), null),
                new SequenceDef(4, "shadow_of_the_veil", "Shadow of the Veil", "Your outline lies about where you are.", ABILITIES_ERROR.get("shadow_of_the_veil"), null),
                new SequenceDef(3, "grand_thief", "Grand Thief", "Steal an ability, a name, or a season.", ABILITIES_ERROR.get("grand_thief"), null),
                new SequenceDef(2, "conceptual_marauder", "Conceptual Marauder", "Rob an idea of its meaning and pawn it.", ABILITIES_ERROR.get("conceptual_marauder"), null),
                new SequenceDef(1, "error", "Error", "You are the typo in creation, and creation keeps failing to fix you.", ABILITIES_ERROR.get("error"), null),
                new SequenceDef(0, "the_mistake", "The Great Mistake", "Something went wrong at the beginning. You are it.", ABILITIES_ERROR.get("the_mistake"), null)
                    )),
            // ---- Mother ----
            new PathwayDef(
                    "mother", "Mother", 0xFF6F8A63, 0xFFE4D3A8,
                    "mother", 9,
                    "Growth without permission. The Mother pathway is generous in the way a flood is generous, and its gardens are full of things that should not flower.",
                    List.of(
                new SequenceDef(9, "planter", "Planter", "Everything you sow comes up, whether or not you sowed it.", ABILITIES_MOTHER.get("planter"), "potion_planter"),
                new SequenceDef(8, "harvester", "Harvester", "Take life in a wide arc and store it for lean years.", ABILITIES_MOTHER.get("harvester"), null),
                new SequenceDef(7, "beast_tamer", "Beast Tamer", "The animal kingdom negotiates with you; you set the terms.", ABILITIES_MOTHER.get("beast_tamer"), null),
                new SequenceDef(6, "herbalist", "Herbalist", "Brews that rewrite a body's opinion of itself.", ABILITIES_MOTHER.get("herbalist"), null),
                new SequenceDef(5, "florist", "Florist", "Plant an instruction and watch the field obey it.", ABILITIES_MOTHER.get("florist"), null),
                new SequenceDef(4, "mother_of_maggots", "Mother of Maggots", "Your children are numberless and they are hungry.", ABILITIES_MOTHER.get("mother_of_maggots"), null),
                new SequenceDef(3, "blight_bringer", "Blight Bringer", "Growth as a weapon: years of rot in one afternoon.", ABILITIES_MOTHER.get("blight_bringer"), null),
                new SequenceDef(2, "green_hand", "Green Hand", "The soil answers to your name; the dead soil apologises.", ABILITIES_MOTHER.get("green_hand"), null),
                new SequenceDef(1, "mother", "Mother", "You are the garden and the gardener and the thing under the soil.", ABILITIES_MOTHER.get("mother"), null),
                new SequenceDef(0, "the_fertile_void", "The Fertile Void", "From nothing, something always grows. Always something.", ABILITIES_MOTHER.get("the_fertile_void"), null)
                    ))
    );

    /** Abilities for pathways that are not yet implemented: registered but inert. */
    private static final List<String> PLACEHOLDER = List.of();

    public static PathwayDef byId(String id) {
        for (PathwayDef p : ALL) {
            if (p.id().equals(id)) return p;
        }
        return ALL.get(0);
    }

    public static PathwayDef byIndex(int index) {
        return ALL.get(Math.max(0, Math.min(ALL.size() - 1, index)));
    }
}
