// GENERATED by tools/gen_java_registries.py from tools/content.py - do not hand-edit.

package com.pathways.beyond.registry;

import net.minecraft.core.registries.Registries;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.StairBlock;
import net.minecraft.world.level.block.WallBlock;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.MapColor;
import net.minecraft.world.level.material.PushReaction;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;

import java.util.function.Supplier;

import static com.pathways.beyond.PathwaysMod.MOD_ID;
import com.pathways.beyond.block.OccultBlocks;

/** Every block plus its BlockItem. Properties are data-driven from tools/content.py. */
public final class ModBlocks {
    private ModBlocks() {}

    public static final DeferredRegister.Blocks BLOCKS = DeferredRegister.createBlocks(MOD_ID);
    public static final DeferredRegister.Items BLOCK_ITEMS = DeferredRegister.createItems(MOD_ID);

    /** ritual_altar */
    public static final DeferredBlock<Block> RitualAltar = BLOCKS.register("ritual_altar",
            () -> OccultBlocks.SimpleBlockFactory.create("ritual_altar", 3.5f, 6.0f, 3, "minecraft:stone", true));
    public static final DeferredItem<BlockItem> RitualAltar_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("ritual_altar", RitualAltar);

    /** ritual_pedestal */
    public static final DeferredBlock<Block> RitualPedestal = BLOCKS.register("ritual_pedestal",
            () -> OccultBlocks.SimpleBlockFactory.create("ritual_pedestal", 3.0f, 6.0f, 2, "minecraft:stone", true));
    public static final DeferredItem<BlockItem> RitualPedestal_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("ritual_pedestal", RitualPedestal);

    /** ritual_candle */
    public static final DeferredBlock<Block> RitualCandle = BLOCKS.register("ritual_candle",
            () -> OccultBlocks.SimpleBlockFactory.create("ritual_candle", 0.5f, 0.5f, 11, "minecraft:candle", false));
    public static final DeferredItem<BlockItem> RitualCandle_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("ritual_candle", RitualCandle);

    /** chalk_circle */
    public static final DeferredBlock<Block> ChalkCircle = BLOCKS.register("chalk_circle",
            () -> OccultBlocks.SimpleBlockFactory.create("chalk_circle", 0.1f, 0.1f, 0, "minecraft:stone", false));
    public static final DeferredItem<BlockItem> ChalkCircle_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("chalk_circle", ChalkCircle);

    /** occult_table */
    public static final DeferredBlock<Block> OccultTable = BLOCKS.register("occult_table",
            () -> OccultBlocks.SimpleBlockFactory.create("occult_table", 2.5f, 3.0f, 0, "minecraft:wood", true));
    public static final DeferredItem<BlockItem> OccultTable_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("occult_table", OccultTable);

    /** blood_basin */
    public static final DeferredBlock<Block> BloodBasin = BLOCKS.register("blood_basin",
            () -> OccultBlocks.SimpleBlockFactory.create("blood_basin", 2.5f, 4.0f, 1, "minecraft:stone", true));
    public static final DeferredItem<BlockItem> BloodBasin_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("blood_basin", BloodBasin);

    /** spirit_lantern */
    public static final DeferredBlock<Block> SpiritLantern = BLOCKS.register("spirit_lantern",
            () -> OccultBlocks.SimpleBlockFactory.create("spirit_lantern", 1.5f, 2.0f, 12, "minecraft:lantern", false));
    public static final DeferredItem<BlockItem> SpiritLantern_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("spirit_lantern", SpiritLantern);

    /** occult_archive */
    public static final DeferredBlock<Block> OccultArchive = BLOCKS.register("occult_archive",
            () -> OccultBlocks.SimpleBlockFactory.create("occult_archive", 2.5f, 3.0f, 0, "minecraft:wood", true));
    public static final DeferredItem<BlockItem> OccultArchive_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("occult_archive", OccultArchive);

    /** gothic_bricks */
    public static final DeferredBlock<Block> GothicBricks = BLOCKS.register("gothic_bricks",
            () -> OccultBlocks.SimpleBlockFactory.create("gothic_bricks", 2.5f, 6.0f, 0, "minecraft:stone", true));
    public static final DeferredItem<BlockItem> GothicBricks_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("gothic_bricks", GothicBricks);

    /** gothic_brick_stairs */
    public static final DeferredBlock<Block> GothicBrickStairs = BLOCKS.register("gothic_brick_stairs",
            () -> OccultBlocks.SimpleBlockFactory.create("gothic_brick_stairs", 2.5f, 6.0f, 0, "minecraft:stone", true));
    public static final DeferredItem<BlockItem> GothicBrickStairs_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("gothic_brick_stairs", GothicBrickStairs);

    /** gothic_brick_slab */
    public static final DeferredBlock<Block> GothicBrickSlab = BLOCKS.register("gothic_brick_slab",
            () -> OccultBlocks.SimpleBlockFactory.create("gothic_brick_slab", 2.5f, 6.0f, 0, "minecraft:stone", true));
    public static final DeferredItem<BlockItem> GothicBrickSlab_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("gothic_brick_slab", GothicBrickSlab);

    /** gothic_brick_wall */
    public static final DeferredBlock<Block> GothicBrickWall = BLOCKS.register("gothic_brick_wall",
            () -> OccultBlocks.SimpleBlockFactory.create("gothic_brick_wall", 2.5f, 6.0f, 0, "minecraft:stone", true));
    public static final DeferredItem<BlockItem> GothicBrickWall_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("gothic_brick_wall", GothicBrickWall);

    /** desecrated_stone */
    public static final DeferredBlock<Block> DesecratedStone = BLOCKS.register("desecrated_stone",
            () -> OccultBlocks.SimpleBlockFactory.create("desecrated_stone", 2.0f, 6.0f, 0, "minecraft:stone", true));
    public static final DeferredItem<BlockItem> DesecratedStone_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("desecrated_stone", DesecratedStone);

    /** desecrated_stone_stairs */
    public static final DeferredBlock<Block> DesecratedStoneStairs = BLOCKS.register("desecrated_stone_stairs",
            () -> OccultBlocks.SimpleBlockFactory.create("desecrated_stone_stairs", 2.0f, 6.0f, 0, "minecraft:stone", true));
    public static final DeferredItem<BlockItem> DesecratedStoneStairs_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("desecrated_stone_stairs", DesecratedStoneStairs);

    /** desecrated_stone_slab */
    public static final DeferredBlock<Block> DesecratedStoneSlab = BLOCKS.register("desecrated_stone_slab",
            () -> OccultBlocks.SimpleBlockFactory.create("desecrated_stone_slab", 2.0f, 6.0f, 0, "minecraft:stone", true));
    public static final DeferredItem<BlockItem> DesecratedStoneSlab_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("desecrated_stone_slab", DesecratedStoneSlab);

    /** weathered_plaster */
    public static final DeferredBlock<Block> WeatheredPlaster = BLOCKS.register("weathered_plaster",
            () -> OccultBlocks.SimpleBlockFactory.create("weathered_plaster", 1.6f, 3.0f, 0, "minecraft:stone", true));
    public static final DeferredItem<BlockItem> WeatheredPlaster_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("weathered_plaster", WeatheredPlaster);

    /** dark_planks */
    public static final DeferredBlock<Block> DarkPlanks = BLOCKS.register("dark_planks",
            () -> OccultBlocks.SimpleBlockFactory.create("dark_planks", 2.0f, 3.0f, 0, "minecraft:wood", true));
    public static final DeferredItem<BlockItem> DarkPlanks_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("dark_planks", DarkPlanks);

    /** dark_plank_stairs */
    public static final DeferredBlock<Block> DarkPlankStairs = BLOCKS.register("dark_plank_stairs",
            () -> OccultBlocks.SimpleBlockFactory.create("dark_plank_stairs", 2.0f, 3.0f, 0, "minecraft:wood", true));
    public static final DeferredItem<BlockItem> DarkPlankStairs_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("dark_plank_stairs", DarkPlankStairs);

    /** dark_plank_slab */
    public static final DeferredBlock<Block> DarkPlankSlab = BLOCKS.register("dark_plank_slab",
            () -> OccultBlocks.SimpleBlockFactory.create("dark_plank_slab", 2.0f, 3.0f, 0, "minecraft:wood", true));
    public static final DeferredItem<BlockItem> DarkPlankSlab_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("dark_plank_slab", DarkPlankSlab);

    /** iron_grate */
    public static final DeferredBlock<Block> IronGrate = BLOCKS.register("iron_grate",
            () -> OccultBlocks.SimpleBlockFactory.create("iron_grate", 2.5f, 6.0f, 0, "minecraft:metal", true));
    public static final DeferredItem<BlockItem> IronGrate_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("iron_grate", IronGrate);

    /** slate_tiles */
    public static final DeferredBlock<Block> SlateTiles = BLOCKS.register("slate_tiles",
            () -> OccultBlocks.SimpleBlockFactory.create("slate_tiles", 2.2f, 6.0f, 0, "minecraft:stone", true));
    public static final DeferredItem<BlockItem> SlateTiles_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("slate_tiles", SlateTiles);

    /** slate_tile_stairs */
    public static final DeferredBlock<Block> SlateTileStairs = BLOCKS.register("slate_tile_stairs",
            () -> OccultBlocks.SimpleBlockFactory.create("slate_tile_stairs", 2.2f, 6.0f, 0, "minecraft:stone", true));
    public static final DeferredItem<BlockItem> SlateTileStairs_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("slate_tile_stairs", SlateTileStairs);

    /** slate_tile_slab */
    public static final DeferredBlock<Block> SlateTileSlab = BLOCKS.register("slate_tile_slab",
            () -> OccultBlocks.SimpleBlockFactory.create("slate_tile_slab", 2.2f, 6.0f, 0, "minecraft:stone", true));
    public static final DeferredItem<BlockItem> SlateTileSlab_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("slate_tile_slab", SlateTileSlab);

    /** veil_glass */
    public static final DeferredBlock<Block> VeilGlass = BLOCKS.register("veil_glass",
            () -> OccultBlocks.SimpleBlockFactory.create("veil_glass", 0.4f, 0.4f, 3, "minecraft:glass", false));
    public static final DeferredItem<BlockItem> VeilGlass_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("veil_glass", VeilGlass);

    /** void_stone */
    public static final DeferredBlock<Block> VoidStone = BLOCKS.register("void_stone",
            () -> OccultBlocks.SimpleBlockFactory.create("void_stone", 3.0f, 9.0f, 0, "minecraft:stone", true));
    public static final DeferredItem<BlockItem> VoidStone_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("void_stone", VoidStone);

    /** spirit_flower */
    public static final DeferredBlock<Block> SpiritFlower = BLOCKS.register("spirit_flower",
            () -> OccultBlocks.SimpleBlockFactory.create("spirit_flower", 0.0f, 0.0f, 7, "minecraft:grass", false));
    public static final DeferredItem<BlockItem> SpiritFlower_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("spirit_flower", SpiritFlower);

    /** moonlit_fungus */
    public static final DeferredBlock<Block> MoonlitFungus = BLOCKS.register("moonlit_fungus",
            () -> OccultBlocks.SimpleBlockFactory.create("moonlit_fungus", 0.0f, 0.0f, 6, "minecraft:grass", false));
    public static final DeferredItem<BlockItem> MoonlitFungus_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("moonlit_fungus", MoonlitFungus);

    /** memory_shard_block */
    public static final DeferredBlock<Block> MemoryShardBlock = BLOCKS.register("memory_shard_block",
            () -> OccultBlocks.SimpleBlockFactory.create("memory_shard_block", 2.5f, 6.0f, 5, "minecraft:stone", true));
    public static final DeferredItem<BlockItem> MemoryShardBlock_ITEM =
            BLOCK_ITEMS.registerSimpleBlockItem("memory_shard_block", MemoryShardBlock);

    public static void register(net.neoforged.bus.api.IEventBus bus) {
        BLOCKS.register(bus);
        BLOCK_ITEMS.register(bus);
    }
}
