// GENERATED by tools/gen_java_registries.py from tools/content.py - do not hand-edit.

package com.pathways.beyond.registry;

import net.minecraft.core.registries.Registries;
import net.minecraft.world.effect.MobEffect;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

import static com.pathways.beyond.PathwaysMod.MOD_ID;
import com.pathways.beyond.effect.OccultEffects;

/** Mob effects. Behaviour lives in effect/OccultEffects. */
public final class ModEffects {
    private ModEffects() {}

    public static final DeferredRegister<MobEffect> EFFECTS =
            DeferredRegister.create(Registries.MOB_EFFECT, MOD_ID);

    /** Sanity Bleed - Drains Sanity continuously. */
    public static final DeferredHolder<MobEffect, MobEffect> SanityBleed =
            EFFECTS.register("sanity_bleed", () -> OccultEffects.create("sanity_bleed"));
    /** Hallucinating - Forces hallucinations regardless of Sanity tier. */
    public static final DeferredHolder<MobEffect, MobEffect> Hallucinating =
            EFFECTS.register("hallucinating", () -> OccultEffects.create("hallucinating"));
    /** Spirit Form - Soul projection: translucent spirit body. */
    public static final DeferredHolder<MobEffect, MobEffect> SpiritForm =
            EFFECTS.register("spirit_form", () -> OccultEffects.create("spirit_form"));
    /** Corruption Surge - Corruption climbs quickly; power climbs with it. */
    public static final DeferredHolder<MobEffect, MobEffect> CorruptionSurge =
            EFFECTS.register("corruption_surge", () -> OccultEffects.create("corruption_surge"));
    /** Thread Bond - A Soul Thread is attached to you. */
    public static final DeferredHolder<MobEffect, MobEffect> ThreadBond =
            EFFECTS.register("thread_bond", () -> OccultEffects.create("thread_bond"));
    /** Unblinking Gaze - You are being observed; Sanity drains and mobs track you. */
    public static final DeferredHolder<MobEffect, MobEffect> UnblinkingGaze =
            EFFECTS.register("unblinking_gaze", () -> OccultEffects.create("unblinking_gaze"));
    /** Curse of the Veil - Failed ritual backlash: random hallucinations + mob hostility. */
    public static final DeferredHolder<MobEffect, MobEffect> CurseOfTheVeil =
            EFFECTS.register("curse_of_the_veil", () -> OccultEffects.create("curse_of_the_veil"));
    /** Clarity - A prepared mind: Sanity loss reduced, hallucination immunity. */
    public static final DeferredHolder<MobEffect, MobEffect> Clarity =
            EFFECTS.register("clarity", () -> OccultEffects.create("clarity"));
    /** Digestion Quickened - Pathway potion digests noticeably faster. */
    public static final DeferredHolder<MobEffect, MobEffect> DigestionQuickened =
            EFFECTS.register("digestion_quickened", () -> OccultEffects.create("digestion_quickened"));
    /** Cosmic Dread - Endgame. Everything knows where you are. */
    public static final DeferredHolder<MobEffect, MobEffect> CosmicDread =
            EFFECTS.register("cosmic_dread", () -> OccultEffects.create("cosmic_dread"));

    public static void register(net.neoforged.bus.api.IEventBus bus) {
        EFFECTS.register(bus);
    }
}
