// GENERATED by tools/gen_java_registries.py from tools/content.py - do not hand-edit.

package com.pathways.beyond.registry;

import net.minecraft.core.registries.Registries;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

import static com.pathways.beyond.PathwaysMod.MOD_ID;
import com.pathways.beyond.entity.OccultEntities;
import com.pathways.beyond.entity.boss.ChoirmasterEntity;
import com.pathways.beyond.entity.boss.UnblinkingEntity;

/** Every supernatural creature and boss. Attributes are registered in EntityEvents. */
public final class ModEntities {
    private ModEntities() {}

    public static final DeferredRegister<EntityType<?>> ENTITIES =
            DeferredRegister.create(Registries.ENTITY_TYPE, MOD_ID);

    /** watcher */
    public static final DeferredHolder<EntityType<?>, EntityType<OccultEntities.WatcherEntity>> Watcher =
            ENTITIES.register("watcher", () -> EntityType.Builder.of(OccultEntities.WatcherEntity::new, MobCategory.MONSTER)
                    .sized(0.6f, 2.6f)
                    .clientTrackingRange(10)
                    .build("watcher"));

    /** hollow */
    public static final DeferredHolder<EntityType<?>, EntityType<OccultEntities.HollowEntity>> Hollow =
            ENTITIES.register("hollow", () -> EntityType.Builder.of(OccultEntities.HollowEntity::new, MobCategory.MONSTER)
                    .sized(0.6f, 2.0f)
                    .clientTrackingRange(10)
                    .build("hollow"));

    /** whispering_husk */
    public static final DeferredHolder<EntityType<?>, EntityType<OccultEntities.WhisperingHuskEntity>> WhisperingHusk =
            ENTITIES.register("whispering_husk", () -> EntityType.Builder.of(OccultEntities.WhisperingHuskEntity::new, MobCategory.MONSTER)
                    .sized(0.6f, 1.95f)
                    .clientTrackingRange(10)
                    .build("whispering_husk"));

    /** veil_tenant */
    public static final DeferredHolder<EntityType<?>, EntityType<OccultEntities.VeilTenantEntity>> VeilTenant =
            ENTITIES.register("veil_tenant", () -> EntityType.Builder.of(OccultEntities.VeilTenantEntity::new, MobCategory.MONSTER)
                    .sized(0.7f, 2.1f)
                    .clientTrackingRange(10)
                    .build("veil_tenant"));

    /** spirit_wisp */
    public static final DeferredHolder<EntityType<?>, EntityType<OccultEntities.SpiritWispEntity>> SpiritWisp =
            ENTITIES.register("spirit_wisp", () -> EntityType.Builder.of(OccultEntities.SpiritWispEntity::new, MobCategory.AMBIENT)
                    .sized(0.4f, 0.4f)
                    .clientTrackingRange(10)
                    .build("spirit_wisp"));

    /** player_body_shell */
    public static final DeferredHolder<EntityType<?>, EntityType<OccultEntities.PlayerBodyShellEntity>> PlayerBodyShell =
            ENTITIES.register("player_body_shell", () -> EntityType.Builder.of(OccultEntities.PlayerBodyShellEntity::new, MobCategory.CREATURE)
                    .sized(0.6f, 1.8f)
                    .clientTrackingRange(10)
                    .build("player_body_shell"));

    /** marionette */
    public static final DeferredHolder<EntityType<?>, EntityType<OccultEntities.MarionetteEntity>> Marionette =
            ENTITIES.register("marionette", () -> EntityType.Builder.of(OccultEntities.MarionetteEntity::new, MobCategory.CREATURE)
                    .sized(0.6f, 1.8f)
                    .clientTrackingRange(10)
                    .build("marionette"));

    /** bizarro_clone */
    public static final DeferredHolder<EntityType<?>, EntityType<OccultEntities.BizarroCloneEntity>> BizarroClone =
            ENTITIES.register("bizarro_clone", () -> EntityType.Builder.of(OccultEntities.BizarroCloneEntity::new, MobCategory.CREATURE)
                    .sized(0.6f, 1.8f)
                    .clientTrackingRange(10)
                    .build("bizarro_clone"));

    /** historical_echo */
    public static final DeferredHolder<EntityType<?>, EntityType<OccultEntities.HistoricalEchoEntity>> HistoricalEcho =
            ENTITIES.register("historical_echo", () -> EntityType.Builder.of(OccultEntities.HistoricalEchoEntity::new, MobCategory.AMBIENT)
                    .sized(0.6f, 1.8f)
                    .clientTrackingRange(10)
                    .build("historical_echo"));

    /** choirmaster_of_the_veil */
    public static final DeferredHolder<EntityType<?>, EntityType<ChoirmasterEntity>> ChoirmasterOfTheVeil =
            ENTITIES.register("choirmaster_of_the_veil", () -> EntityType.Builder.of(ChoirmasterEntity::new, MobCategory.MONSTER)
                    .sized(0.75f, 3.4f)
                    .clientTrackingRange(10)
                    .build("choirmaster_of_the_veil"));

    /** the_unblinking */
    public static final DeferredHolder<EntityType<?>, EntityType<UnblinkingEntity>> TheUnblinking =
            ENTITIES.register("the_unblinking", () -> EntityType.Builder.of(UnblinkingEntity::new, MobCategory.MONSTER)
                    .sized(2.4f, 4.6f)
                    .clientTrackingRange(10)
                    .build("the_unblinking"));

    public static void register(net.neoforged.bus.api.IEventBus bus) {
        ENTITIES.register(bus);
    }
}
