// GENERATED by tools/gen_java_registries.py from tools/content.py - do not hand-edit.

package com.pathways.beyond.registry;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.Rarity;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

import static com.pathways.beyond.PathwaysMod.MOD_ID;
import com.pathways.beyond.item.OccultItems;

/** Every item: pathway potions, ingredients, sealed artifacts, occult tools. */
public final class ModItems {
    private ModItems() {}

    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(MOD_ID);

    // ---- pathway potions ----
    /** Seer - fool Sequence 9 */
    public static final DeferredItem<Item> PotionSeer = ITEMS.register("potion_seer",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "fool", 9, 0x4B3068, "veil"));
    /** Clown - fool Sequence 8 */
    public static final DeferredItem<Item> PotionClown = ITEMS.register("potion_clown",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "fool", 8, 0x5A0F17, "rose"));
    /** Magician - fool Sequence 7 */
    public static final DeferredItem<Item> PotionMagician = ITEMS.register("potion_magician",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "fool", 7, 0x21456B, "cyan_mut"));
    /** Faceless - fool Sequence 6 */
    public static final DeferredItem<Item> PotionFaceless = ITEMS.register("potion_faceless",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "fool", 6, 0xCDB583, "bone"));
    /** Marionettist - fool Sequence 5 */
    public static final DeferredItem<Item> PotionMarionettist = ITEMS.register("potion_marionettist",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "fool", 5, 0x2F4232, "moss_hi"));
    /** Bizarro Sorcerer - fool Sequence 4 */
    public static final DeferredItem<Item> PotionBizarroSorcerer = ITEMS.register("potion_bizarro_sorcerer",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "fool", 4, 0x7B5AA0, "orchid"));
    /** Scholar of Yore - fool Sequence 3 */
    public static final DeferredItem<Item> PotionScholar = ITEMS.register("potion_scholar",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "fool", 3, 0x7E5A34, "khaki"));
    /** Miracle Invoker - fool Sequence 2 */
    public static final DeferredItem<Item> PotionMiracleInvoker = ITEMS.register("potion_miracle_invoker",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "fool", 2, 0xEBD08A, "gold"));
    /** Attendant of Mysteries - fool Sequence 1 */
    public static final DeferredItem<Item> PotionAttendant = ITEMS.register("potion_attendant",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "fool", 1, 0xA8DCE2, "spirit"));
    /** The Fool - fool Sequence 0 */
    public static final DeferredItem<Item> PotionTheFool = ITEMS.register("potion_the_fool",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "fool", 0, 0xF6F3F8, "white"));
    /** Bard - sun Sequence 9 */
    public static final DeferredItem<Item> PotionBard = ITEMS.register("potion_bard",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "sun", 9, 0x9C7C3A, "gold"));
    /** Corpse Collector - death Sequence 9 */
    public static final DeferredItem<Item> PotionCorpseCollector = ITEMS.register("potion_corpse_collector",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "death", 9, 0x2F4232, "sage"));
    /** Apprentice - door Sequence 9 */
    public static final DeferredItem<Item> PotionApprentice = ITEMS.register("potion_apprentice",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "door", 9, 0x13273F, "blue"));
    /** Spectator - visionary Sequence 9 */
    public static final DeferredItem<Item> PotionSpectator = ITEMS.register("potion_spectator",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "visionary", 9, 0x3A6C96, "cyan_mut"));
    /** Lawyer - black_emperor Sequence 9 */
    public static final DeferredItem<Item> PotionLawyer = ITEMS.register("potion_lawyer",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "black_emperor", 9, 0x3E2A1B, "brass"));
    /** Marauder - error Sequence 9 */
    public static final DeferredItem<Item> PotionMarauder = ITEMS.register("potion_marauder",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "error", 9, 0x191519, "rust"));
    /** Planter - mother Sequence 9 */
    public static final DeferredItem<Item> PotionPlanter = ITEMS.register("potion_planter",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "mother", 9, 0x4C6749, "sage"));
    /** Gravedigger - death Sequence 8 */
    public static final DeferredItem<Item> PotionGravedigger = ITEMS.register("potion_gravedigger",
            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), "death", 8, 0x262128, "smoke"));

    // ---- supernatural ingredients ----
    /** Spirit Flower - Blooms on graves and battlefields at night */
    public static final DeferredItem<Item> SpiritFlower = ITEMS.register("spirit_flower",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 1));
    /** Moonlit Fungus - Caves and cellars, only under moonlight */
    public static final DeferredItem<Item> MoonlitFungus = ITEMS.register("moonlit_fungus",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 1));
    /** Veil Dust - Swept from ritual circles and haunted thresholds */
    public static final DeferredItem<Item> VeilDust = ITEMS.register("veil_dust",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 1));
    /** Purified Salt - Bought, blessed, or stolen from a chapel */
    public static final DeferredItem<Item> PurifiedSalt = ITEMS.register("purified_salt",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 1));
    /** Occult Chalk - Crafted from salt, bone ash and grave earth */
    public static final DeferredItem<Item> OccultChalk = ITEMS.register("occult_chalk",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 2));
    /** Grave Earth - Dug from freshly turned soil */
    public static final DeferredItem<Item> GraveEarth = ITEMS.register("grave_earth",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 2));
    /** Whispering Bone - Rare drop from the Whispering Husk */
    public static final DeferredItem<Item> WhisperingBone = ITEMS.register("whispering_bone",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 2));
    /** Silver Needle - Silversmithing workbench */
    public static final DeferredItem<Item> SilverNeedle = ITEMS.register("silver_needle",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 2));
    /** Starless Crystal - Deep underground, below y=0 */
    public static final DeferredItem<Item> StarlessCrystal = ITEMS.register("starless_crystal",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 3));
    /** Soul Fragment - Severed Soul Threads and Spirit World motes */
    public static final DeferredItem<Item> SoulFragment = ITEMS.register("soul_fragment",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 3));
    /** Abyssal Eye - Fished out of the deep dark and from Hollow remains */
    public static final DeferredItem<Item> AbyssalEye = ITEMS.register("abyssal_eye",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 3));
    /** Black Blood - Collected from tainted animals and corruption pools */
    public static final DeferredItem<Item> BlackBloodVial = ITEMS.register("black_blood_vial",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 3));
    /** Faceless Skin - Shed by a Faceless in the middle of a change */
    public static final DeferredItem<Item> FacelessSkin = ITEMS.register("faceless_skin",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 4));
    /** Corrupted Heart - Pulled from a mob killed at Corruption 80+ */
    public static final DeferredItem<Item> CorruptedHeart = ITEMS.register("corrupted_heart",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 4));
    /** Ancient Memory - Harvested with Scholar of Yore from remembered places */
    public static final DeferredItem<Item> AncientMemory = ITEMS.register("ancient_memory",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 4));
    /** Nightshade Ashes - Burned offerings at a ritual altar */
    public static final DeferredItem<Item> NightshadeAshes = ITEMS.register("nightshade_ashes",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 4));

    // ---- sealed artifacts ----
    /** The Eye of Solomon - A brass-and-glass eye set in a sealed reliquary. The pupil tracks things with no bodies. */
    public static final DeferredItem<Item> EyeOfSolomon = ITEMS.register("eye_of_solomon",
            () -> new OccultItems.EyeOfSolomonItem(new Item.Properties().stacksTo(1).rarity(Rarity.RARE)));
    /** The Black Book - Bound in something that was never an animal. The pages rearrange while you read them. */
    public static final DeferredItem<Item> BlackBook = ITEMS.register("black_book",
            () -> new OccultItems.BlackBookItem(new Item.Properties().stacksTo(1).rarity(Rarity.RARE)));
    /** The Whispering Bell - A cracked brass bell. Its clapper was removed by someone who was careful. */
    public static final DeferredItem<Item> WhisperingBell = ITEMS.register("whispering_bell",
            () -> new OccultItems.WhisperingBellItem(new Item.Properties().stacksTo(1).rarity(Rarity.UNCOMMON)));
    /** The Brass Key - A key with no matching lock, warm to the touch, engraved 'FOR EMERGENCIES ONLY'. */
    public static final DeferredItem<Item> BrassKey = ITEMS.register("brass_key",
            () -> new OccultItems.BrassKeyItem(new Item.Properties().stacksTo(1).rarity(Rarity.RARE)));

    // ---- occult tools ----
    /** Pathway Codex - Victorian occult ledger: Pathway screen, Sequences, digestion and lore. */
    public static final DeferredItem<Item> PathwayCodex = ITEMS.register("pathway_codex",
            () -> new OccultItems.CodexItem(new Item.Properties().stacksTo(1)));
    /** Spool of Soul Thread - Crafting component; the raw material of binding. */
    public static final DeferredItem<Item> SoulThreadSpool = ITEMS.register("soul_thread_spool",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties().stacksTo(1)));
    /** Thread Shears - Cut a bound Soul Thread. The puppet remembers being cut. */
    public static final DeferredItem<Item> ThreadShears = ITEMS.register("thread_shears",
            () -> new OccultItems.ThreadShearsItem(new Item.Properties().stacksTo(1)));
    /** Ritual Dagger - Open a palm for the circle; provides ritual blood. */
    public static final DeferredItem<Item> RitualDagger = ITEMS.register("ritual_dagger",
            () -> new OccultItems.RitualDaggerItem(new Item.Properties().stacksTo(1)));
    /** Occult Compass - Points to the nearest supernatural structure or active ritual. */
    public static final DeferredItem<Item> OccultCompass = ITEMS.register("occult_compass",
            () -> new OccultItems.OccultCompassItem(new Item.Properties().stacksTo(1)));
    /** Ward Charm - Slows Sanity loss and blocks one possession attempt. Then it is spent. */
    public static final DeferredItem<Item> WardCharm = ITEMS.register("ward_charm",
            () -> new OccultItems.WardCharmItem(new Item.Properties().stacksTo(1)));
    /** Spirit Tonic - Restores Sanity at the cost of a temporary Corruption tick. */
    public static final DeferredItem<Item> SpiritTonic = ITEMS.register("spirit_tonic",
            () -> new OccultItems.SpiritTonicItem(new Item.Properties().stacksTo(1)));

    // ---- drops ----
    public static final DeferredItem<Item> CORRUPTED_HEART_DROP = ITEMS.register("corrupted_heart",
            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 4));

    private static String rarityName(int tier) {
        return switch (tier) {
            case 2 -> "UNCOMMON";
            case 3 -> "RARE";
            case 4, 5 -> "EPIC";
            default -> "COMMON";
        };
    }

    public static void register(net.neoforged.bus.api.IEventBus bus) {
        ITEMS.register(bus);
    }
}
