// GENERATED by tools/gen_java_registries.py from tools/content.py - do not hand-edit.

package com.pathways.beyond.registry;

import net.minecraft.core.particles.ParticleType;
import net.minecraft.core.particles.SimpleParticleType;
import net.minecraft.core.registries.Registries;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

import static com.pathways.beyond.PathwaysMod.MOD_ID;

/** Custom particles: spirit motes, rune dust, black wisps, impossible shards. */
public final class ModParticles {
    private ModParticles() {}

    public static final DeferredRegister<ParticleType<?>> PARTICLES =
            DeferredRegister.create(Registries.PARTICLE_TYPE, MOD_ID);

    /** soft round mote that drifts upward and fades - spirit world ambience */
    public static final DeferredHolder<ParticleType<?>, SimpleParticleType> SpiritMote =
            PARTICLES.register("spirit_mote", () -> new SimpleParticleType(false));
    /** square-edged glyph flake that spins as it falls - ritual circles */
    public static final DeferredHolder<ParticleType<?>, SimpleParticleType> RuneDust =
            PARTICLES.register("rune_dust", () -> new SimpleParticleType(false));
    /** candle ember with a slow flicker - candles, altars, forbidden rooms */
    public static final DeferredHolder<ParticleType<?>, SimpleParticleType> EmberOccult =
            PARTICLES.register("ember_occult", () -> new SimpleParticleType(false));
    /** short-lived shadow wisp that smears - corruption */
    public static final DeferredHolder<ParticleType<?>, SimpleParticleType> BlackWisp =
            PARTICLES.register("black_wisp", () -> new SimpleParticleType(false));
    /** hard-edged speck with a violet/cyan split - sanity distortion */
    public static final DeferredHolder<ParticleType<?>, SimpleParticleType> ChromaticSpeck =
            PARTICLES.register("chromatic_speck", () -> new SimpleParticleType(false));
    /** teardrop mote that travels along Soul Threads - threads, puppets */
    public static final DeferredHolder<ParticleType<?>, SimpleParticleType> SoulFlow =
            PARTICLES.register("soul_flow", () -> new SimpleParticleType(false));
    /** low, wide smoke that hugs the ground - failures, veil thinning */
    public static final DeferredHolder<ParticleType<?>, SimpleParticleType> VeilSmoke =
            PARTICLES.register("veil_smoke", () -> new SimpleParticleType(false));
    /** impossible polygon that rotates on two axes - The Beyond */
    public static final DeferredHolder<ParticleType<?>, SimpleParticleType> BeyondShard =
            PARTICLES.register("beyond_shard", () -> new SimpleParticleType(false));
    /** small dark droplet with gravity - ritual blood */
    public static final DeferredHolder<ParticleType<?>, SimpleParticleType> BloodDrop =
            PARTICLES.register("blood_drop", () -> new SimpleParticleType(false));
    /** hard-edged dark smear that slides sideways - dodges, folds, failed teleports */
    public static final DeferredHolder<ParticleType<?>, SimpleParticleType> ShadowMove =
            PARTICLES.register("shadow_move", () -> new SimpleParticleType(false));

    public static void register(net.neoforged.bus.api.IEventBus bus) {
        PARTICLES.register(bus);
    }
}
