// GENERATED by tools/gen_java_registries.py from tools/content.py - do not hand-edit.

package com.pathways.beyond.registry;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

import static com.pathways.beyond.PathwaysMod.MOD_ID;

/** Every sound in the mod. Files live in assets/pathwaysofthebeyond/sounds/*.ogg (procedurally synthesized). */
public final class ModSounds {
    private ModSounds() {}

    public static final DeferredRegister<SoundEvent> SOUNDS =
            DeferredRegister.create(Registries.SOUND_EVENT, MOD_ID);

    /** wet, resonant swallow with a low bell tail */
    public static final DeferredHolder<SoundEvent, SoundEvent> PotionDrink = register("potion_drink");
    /** slow bubbling under a held breath */
    public static final DeferredHolder<SoundEvent, SoundEvent> PotionBrew = register("potion_brew");
    /** glass stopper, then a sigh that is not yours */
    public static final DeferredHolder<SoundEvent, SoundEvent> PotionFinish = register("potion_finish");
    /** leather creak, brass clasp, distant page-turn */
    public static final DeferredHolder<SoundEvent, SoundEvent> CodexOpen = register("codex_open");
    /** dry page, ink scratch, whisper underneath */
    public static final DeferredHolder<SoundEvent, SoundEvent> CodexPage = register("codex_page");
    /** cracked brass bell, no clapper */
    public static final DeferredHolder<SoundEvent, SoundEvent> BellRing = register("bell_ring");
    /** something very large answers, from very far away */
    public static final DeferredHolder<SoundEvent, SoundEvent> BellAnswer = register("bell_answer");
    /** brass mechanism, breath intake, hum */
    public static final DeferredHolder<SoundEvent, SoundEvent> ArtifactActivate = register("artifact_activate");
    /** deal closing: reversed chime and a soft laugh */
    public static final DeferredHolder<SoundEvent, SoundEvent> ArtifactCurse = register("artifact_curse");
    /** fibre tightening, wet click */
    public static final DeferredHolder<SoundEvent, SoundEvent> ThreadBind = register("thread_bind");
    /** taut string snapping inside flesh */
    public static final DeferredHolder<SoundEvent, SoundEvent> ThreadSever = register("thread_sever");
    /** rising string drone, off-key */
    public static final DeferredHolder<SoundEvent, SoundEvent> ThreadTension = register("thread_tension");
    /** gritty scrape with a faint glassy overtone */
    public static final DeferredHolder<SoundEvent, SoundEvent> ChalkDraw = register("chalk_draw");
    /** shallow cut, blood hitting stone */
    public static final DeferredHolder<SoundEvent, SoundEvent> DaggerCut = register("dagger_cut");
    /** candles catching one by one, then a chord */
    public static final DeferredHolder<SoundEvent, SoundEvent> RitualStart = register("ritual_start");
    /** looping drone: organ, breathing, brittle metronome */
    public static final DeferredHolder<SoundEvent, SoundEvent> RitualLoop = register("ritual_loop");
    /** glyphs flash: filtered thump and reversed cymbal */
    public static final DeferredHolder<SoundEvent, SoundEvent> RitualPulse = register("ritual_pulse");
    /** layered wordless chant, no vowels */
    public static final DeferredHolder<SoundEvent, SoundEvent> RitualChant = register("ritual_chant");
    /** chord resolving upward into a closing door */
    public static final DeferredHolder<SoundEvent, SoundEvent> RitualComplete = register("ritual_complete");
    /** a dropped instrument, then a room exhaling */
    public static final DeferredHolder<SoundEvent, SoundEvent> RitualFail = register("ritual_fail");
    /** a voice at conversational distance, no words */
    public static final DeferredHolder<SoundEvent, SoundEvent> WhisperNear = register("whisper_near");
    /** many voices in another room */
    public static final DeferredHolder<SoundEvent, SoundEvent> WhisperFar = register("whisper_far");
    /** two-thump heartbeat, slowly becoming two heartbeats */
    public static final DeferredHolder<SoundEvent, SoundEvent> Heartbeat = register("heartbeat");
    /** breath that lands slightly out of sync with yours */
    public static final DeferredHolder<SoundEvent, SoundEvent> Breathing = register("breathing");
    /** three flat knocks, wood and knuckle */
    public static final DeferredHolder<SoundEvent, SoundEvent> Knock = register("knock");
    /** sub-bass pressure, felt more than heard */
    public static final DeferredHolder<SoundEvent, SoundEvent> Rumble = register("rumble");
    /** tape hiss with a periodic buried tone */
    public static final DeferredHolder<SoundEvent, SoundEvent> Static = register("static");
    /** attention focusing, high thin tone */
    public static final DeferredHolder<SoundEvent, SoundEvent> WatcherStare = register("watcher_stare");
    /** air closing where something stood */
    public static final DeferredHolder<SoundEvent, SoundEvent> WatcherVanish = register("watcher_vanish");
    /** one bare footstep, longer stride than a human's */
    public static final DeferredHolder<SoundEvent, SoundEvent> HollowStep = register("hollow_step");
    /** wet joint adjustments and a held breath */
    public static final DeferredHolder<SoundEvent, SoundEvent> HollowIdle = register("hollow_idle");
    /** several voices layered inside one throat */
    public static final DeferredHolder<SoundEvent, SoundEvent> HuskWhisper = register("husk_whisper");
    /** sudden lunge with a vocal crack */
    public static final DeferredHolder<SoundEvent, SoundEvent> HuskAttack = register("husk_attack");
    /** wooden joint click on string tension */
    public static final DeferredHolder<SoundEvent, SoundEvent> MarionetteJoint = register("marionette_joint");
    /** liturgical melody sung slightly flat */
    public static final DeferredHolder<SoundEvent, SoundEvent> ChoirmasterChant = register("choirmaster_chant");
    /** choir all inhaling at once then breaking */
    public static final DeferredHolder<SoundEvent, SoundEvent> ChoirmasterScream = register("choirmaster_scream");
    /** an enormous lid opening in a small room */
    public static final DeferredHolder<SoundEvent, SoundEvent> UnblinkingGaze = register("unblinking_gaze");
    /** glass and fluid cracking together */
    public static final DeferredHolder<SoundEvent, SoundEvent> UnblinkingHurt = register("unblinking_hurt");
    /** the eye closes: pressure release and long decay */
    public static final DeferredHolder<SoundEvent, SoundEvent> UnblinkingDeath = register("unblinking_death");
    /** a body being entered and disagreeing */
    public static final DeferredHolder<SoundEvent, SoundEvent> TenantPossess = register("tenant_possess");
    /** upward surge, bells, then a heartbeat that is not yours */
    public static final DeferredHolder<SoundEvent, SoundEvent> SequenceAdvance = register("sequence_advance");
    /** stomach settling in a body that has changed */
    public static final DeferredHolder<SoundEvent, SoundEvent> SequenceDigest = register("sequence_digest");
    /** black vein crawling under skin, close mic */
    public static final DeferredHolder<SoundEvent, SoundEvent> CorruptionPulse = register("corruption_pulse");
    /** the veil parting: reverse reverb and cold */
    public static final DeferredHolder<SoundEvent, SoundEvent> SpiritEnter = register("spirit_enter");
    /** returning too fast, ringing in the ears */
    public static final DeferredHolder<SoundEvent, SoundEvent> SpiritExit = register("spirit_exit");
    /** looping desolate wind and distant impossibilities */
    public static final DeferredHolder<SoundEvent, SoundEvent> SpiritAmbient = register("spirit_ambient");
    /** soul tether stretching past tolerance */
    public static final DeferredHolder<SoundEvent, SoundEvent> SpiritStrain = register("spirit_strain");
    /** tether parting; a caught breath */
    public static final DeferredHolder<SoundEvent, SoundEvent> SpiritSnap = register("spirit_snap");
    /** sky shifting colour: low brass swell */
    public static final DeferredHolder<SoundEvent, SoundEvent> RedMoon = register("red_moon");
    /** fabric tearing, very slowly, in every direction */
    public static final DeferredHolder<SoundEvent, SoundEvent> VeilThins = register("veil_thins");
    /** the whole world whispering in one long breath */
    public static final DeferredHolder<SoundEvent, SoundEvent> WhisperingNight = register("whispering_night");
    /** a place remembering: reversed ambience and one distant event */
    public static final DeferredHolder<SoundEvent, SoundEvent> MemoryEcho = register("memory_echo");
    /** skin and features rearranging, close mic */
    public static final DeferredHolder<SoundEvent, SoundEvent> FacelessShift = register("faceless_shift");
    /** a command given in a language with no vowels */
    public static final DeferredHolder<SoundEvent, SoundEvent> AuthorityForbid = register("authority_forbid");
    /** an inverted bell, a long way below */
    public static final DeferredHolder<SoundEvent, SoundEvent> BeyondCall = register("beyond_call");
    /** the sound of being noticed by something patient */
    public static final DeferredHolder<SoundEvent, SoundEvent> BeyondArrival = register("beyond_arrival");

    private static DeferredHolder<SoundEvent, SoundEvent> register(String name) {
        ResourceLocation id = ResourceLocation.fromNamespaceAndPath(MOD_ID, name);
        return SOUNDS.register(name, () -> SoundEvent.createVariableRangeEvent(id));
    }

    public static void register(net.neoforged.bus.api.IEventBus bus) {
        SOUNDS.register(bus);
    }
}
