// GENERATED by tools/gen_java_registries.py from tools/content.py - do not hand-edit.

package com.pathways.beyond.registry;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

import static com.pathways.beyond.PathwaysMod.MOD_ID;

/** Four creative tabs: the whole mod reads as one curated expansion, not a dump. */
public final class ModTabs {
    private ModTabs() {}

    public static final DeferredRegister<CreativeModeTab> TABS =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, MOD_ID);

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> Pathways =
            TABS.register("pathways", () -> CreativeModeTab.builder()
                    .title(Component.translatable("itemGroup.pathwaysofthebeyond.pathways"))
                    .icon(() -> icon("pathway_codex"))
                    .displayItems((params, output) -> TabContents.fill("pathways", output))
                    .build());

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> PathwayRitual =
            TABS.register("pathway_ritual", () -> CreativeModeTab.builder()
                    .title(Component.translatable("itemGroup.pathwaysofthebeyond.pathway_ritual"))
                    .icon(() -> icon("ritual_altar"))
                    .displayItems((params, output) -> TabContents.fill("pathway_ritual", output))
                    .build());

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> PathwayArtifacts =
            TABS.register("pathway_artifacts", () -> CreativeModeTab.builder()
                    .title(Component.translatable("itemGroup.pathwaysofthebeyond.pathway_artifacts"))
                    .icon(() -> icon("eye_of_solomon"))
                    .displayItems((params, output) -> TabContents.fill("pathway_artifacts", output))
                    .build());

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> PathwayBeyond =
            TABS.register("pathway_beyond", () -> CreativeModeTab.builder()
                    .title(Component.translatable("itemGroup.pathwaysofthebeyond.pathway_beyond"))
                    .icon(() -> icon("void_stone"))
                    .displayItems((params, output) -> TabContents.fill("pathway_beyond", output))
                    .build());

    /** Lazy icon lookup: tab icons are evaluated after every registry is populated. */
    private static ItemStack icon(String id) {
        return new ItemStack(net.minecraft.core.registries.BuiltInRegistries.ITEM.get(
                net.minecraft.resources.ResourceLocation.fromNamespaceAndPath(MOD_ID, id)));
    }

    public static void register(net.neoforged.bus.api.IEventBus bus) {
        TABS.register(bus);
    }
}
