// GENERATED by tools/gen_java_registries.py from tools/content.py - do not hand-edit.

package com.pathways.beyond.registry;

import java.util.List;
import java.util.Map;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;

import static com.pathways.beyond.PathwaysMod.MOD_ID;

/** Curated creative-tab contents: each tab reads as a set, not a pile. */
public final class TabContents {
    private TabContents() {}

    private static final Map<String, List<String>> BY_TAB = Map.of(
            "pathways", List.of(
                    "potion_seer",
                    "potion_clown",
                    "potion_magician",
                    "potion_faceless",
                    "potion_marionettist",
                    "potion_bizarro_sorcerer",
                    "potion_scholar",
                    "potion_miracle_invoker",
                    "potion_attendant",
                    "potion_the_fool",
                    "potion_bard",
                    "potion_corpse_collector",
                    "potion_apprentice",
                    "potion_spectator",
                    "potion_lawyer",
                    "potion_marauder",
                    "potion_planter",
                    "potion_gravedigger",
                    "pathway_codex"
            ),
            "pathway_ritual", List.of(
                    "ritual_altar",
                    "ritual_pedestal",
                    "ritual_candle",
                    "chalk_circle",
                    "occult_table",
                    "blood_basin",
                    "spirit_lantern",
                    "occult_archive",
                    "gothic_bricks",
                    "gothic_brick_stairs",
                    "gothic_brick_slab",
                    "gothic_brick_wall",
                    "desecrated_stone",
                    "desecrated_stone_stairs",
                    "desecrated_stone_slab",
                    "weathered_plaster",
                    "dark_planks",
                    "dark_plank_stairs",
                    "dark_plank_slab",
                    "iron_grate",
                    "slate_tiles",
                    "slate_tile_stairs",
                    "slate_tile_slab",
                    "veil_glass",
                    "spirit_flower",
                    "moonlit_fungus",
                    "spirit_flower",
                    "moonlit_fungus",
                    "veil_dust",
                    "purified_salt",
                    "occult_chalk",
                    "grave_earth",
                    "whispering_bone",
                    "silver_needle",
                    "soul_fragment",
                    "black_blood_vial",
                    "faceless_skin",
                    "nightshade_ashes",
                    "ritual_dagger"
            ),
            "pathway_artifacts", List.of(
                    "eye_of_solomon",
                    "black_book",
                    "whispering_bell",
                    "brass_key",
                    "thread_shears",
                    "soul_thread_spool",
                    "occult_compass",
                    "ward_charm",
                    "spirit_tonic"
            ),
            "pathway_beyond", List.of(
                    "void_stone",
                    "memory_shard_block",
                    "starless_crystal",
                    "abyssal_eye",
                    "corrupted_heart",
                    "ancient_memory"
            )
    );

    /** Adds one tab's entries; ids that are missing from the registry are skipped. */
    public static void fill(String tab, CreativeModeTab.Output output) {
        for (String id : BY_TAB.getOrDefault(tab, List.of())) {
            Item item = BuiltInRegistries.ITEM.get(ResourceLocation.fromNamespaceAndPath(MOD_ID, id));
            if (item != Items.AIR) {
                output.accept(item);
            }
        }
    }
}
