"""
Generate Java registries + pathway data from the content index.

Everything the mod registers (blocks, items, entities, effects, particles, sounds,
creative tabs) and all pathway/sequence/lore data is emitted here, so the Java code,
the JSON data pack, the assets and docs all come from tools/content.py. Hand-written
behaviour classes are referenced by name from the mapping tables below.

Run:  python3 tools/gen_java_registries.py
"""
from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from content import (ARTIFACTS, BLOCKS, BOSSES, EFFECTS, INGREDIENTS, MOD_ID, PACKAGE,  # noqa: E402
                     PARTICLES, PATHWAYS, POTIONS, REGULAR_ENTITIES, SOUNDS,
                     SUMMONED_ENTITIES, TABS, UTILITY_ITEMS, CORRUPTION_STAGES,
                     SANITY_TIERS, STRUCTURES, WORLD_EVENTS, CORE_SHADERS, DIMENSIONS)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JAVA = os.path.join(ROOT, "src", "main", "java", "com", "pathways", "beyond")
HEADER = "// GENERATED by tools/gen_java_registries.py from tools/content.py - do not hand-edit.\n"

# ---------------------------------------------------------------------------------------
# behaviour classes: block id -> (java class simple name, extra properties)
# ---------------------------------------------------------------------------------------
BLOCK_CLASSES = {
    "ritual_altar": ("RitualAltarBlock", "altar"),
    "ritual_pedestal": ("RitualPedestalBlock", "pedestal"),
    "ritual_candle": ("RitualCandleBlock", "candle"),
    "chalk_circle": ("ChalkCircleBlock", "chalk"),
    "occult_table": ("OccultTableBlock", "table"),
    "blood_basin": ("BloodBasinBlock", "basin"),
    "spirit_lantern": ("SpiritLanternBlock", "lantern"),
    "occult_archive": ("OccultArchiveBlock", "archive"),
    "memory_shard_block": ("MemoryShardBlock", "shard"),
    "spirit_flower": ("SpiritFlowerBlock", "flower"),
    "moonlit_fungus": ("MoonlitFungusBlock", "fungus"),
    "veil_glass": ("VeilGlassBlock", "glass"),
    "iron_grate": ("IronGrateBlock", "grate"),
}
# simple building blocks share one plain implementation
SIMPLE_BLOCK_KINDS = {"cube", "stairs", "slab", "wall", "plant"}

# block behaviour spec: hardness, resistance, light, sound group, tool, needs tool
BLOCK_SPECS = {
    "ritual_altar": (3.5, 6.0, 3, "minecraft:stone", "pickaxe", True),
    "ritual_pedestal": (3.0, 6.0, 2, "minecraft:stone", "pickaxe", True),
    "ritual_candle": (0.5, 0.5, 11, "minecraft:candle", "none", False),
    "chalk_circle": (0.1, 0.1, 0, "minecraft:stone", "none", False),
    "occult_table": (2.5, 3.0, 0, "minecraft:wood", "axe", True),
    "blood_basin": (2.5, 4.0, 1, "minecraft:stone", "pickaxe", True),
    "spirit_lantern": (1.5, 2.0, 12, "minecraft:lantern", "pickaxe", False),
    "occult_archive": (2.5, 3.0, 0, "minecraft:wood", "axe", True),
    "memory_shard_block": (2.5, 6.0, 5, "minecraft:stone", "pickaxe", True),
    "spirit_flower": (0.0, 0.0, 7, "minecraft:grass", "none", False),
    "moonlit_fungus": (0.0, 0.0, 6, "minecraft:grass", "none", False),
    "veil_glass": (0.4, 0.4, 3, "minecraft:glass", "none", False),
    "iron_grate": (2.5, 6.0, 0, "minecraft:metal", "pickaxe", True),
    "gothic_bricks": (2.5, 6.0, 0, "minecraft:stone", "pickaxe", True),
    "gothic_brick_stairs": (2.5, 6.0, 0, "minecraft:stone", "pickaxe", True),
    "gothic_brick_slab": (2.5, 6.0, 0, "minecraft:stone", "pickaxe", True),
    "gothic_brick_wall": (2.5, 6.0, 0, "minecraft:stone", "pickaxe", True),
    "desecrated_stone": (2.0, 6.0, 0, "minecraft:stone", "pickaxe", True),
    "desecrated_stone_stairs": (2.0, 6.0, 0, "minecraft:stone", "pickaxe", True),
    "desecrated_stone_slab": (2.0, 6.0, 0, "minecraft:stone", "pickaxe", True),
    "weathered_plaster": (1.6, 3.0, 0, "minecraft:stone", "pickaxe", True),
    "dark_planks": (2.0, 3.0, 0, "minecraft:wood", "axe", True),
    "dark_plank_stairs": (2.0, 3.0, 0, "minecraft:wood", "axe", True),
    "dark_plank_slab": (2.0, 3.0, 0, "minecraft:wood", "axe", True),
    "slate_tiles": (2.2, 6.0, 0, "minecraft:stone", "pickaxe", True),
    "slate_tile_stairs": (2.2, 6.0, 0, "minecraft:stone", "pickaxe", True),
    "slate_tile_slab": (2.2, 6.0, 0, "minecraft:stone", "pickaxe", True),
    "void_stone": (3.0, 9.0, 0, "minecraft:stone", "pickaxe", True),
}

# item id -> (behaviour class simple name, constructor arg kind)
ITEM_CLASSES = {
    "pathway_codex": "CodexItem",
    "soul_thread_spool": "SimpleLoreItem",
    "thread_shears": "ThreadShearsItem",
    "ritual_dagger": "RitualDaggerItem",
    "occult_compass": "OccultCompassItem",
    "ward_charm": "WardCharmItem",
    "spirit_tonic": "SpiritTonicItem",
    "eye_of_solomon": "EyeOfSolomonItem",
    "black_book": "BlackBookItem",
    "whispering_bell": "WhisperingBellItem",
    "brass_key": "BrassKeyItem",
}

ENTITY_CLASSES = {
    "watcher": ("WatcherEntity", "MONSTER", 0.6, 2.6),
    "hollow": ("HollowEntity", "MONSTER", 0.6, 2.0),
    "whispering_husk": ("WhisperingHuskEntity", "MONSTER", 0.6, 1.95),
    "veil_tenant": ("VeilTenantEntity", "MONSTER", 0.7, 2.1),
    "spirit_wisp": ("SpiritWispEntity", "AMBIENT", 0.4, 0.4),
    "marionette": ("MarionetteEntity", "CREATURE", 0.6, 1.8),
    "bizarro_clone": ("BizarroCloneEntity", "CREATURE", 0.6, 1.8),
    "historical_echo": ("HistoricalEchoEntity", "AMBIENT", 0.6, 1.8),
    "player_body_shell": ("PlayerBodyShellEntity", "CREATURE", 0.6, 1.8),
    "choirmaster_of_the_veil": ("ChoirmasterEntity", "MONSTER", 0.75, 3.4),
    "the_unblinking": ("UnblinkingEntity", "MONSTER", 2.4, 4.6),
}


def w(path, content):
    full = os.path.join(JAVA, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as f:
        f.write(content)
    print("  wrote", path)


def java_bool(b):
    return "true" if b else "false"


# ---------------------------------------------------------------------------------------
def gen_pathway_data():
    """PathwayData.java: every pathway, sequence, colour, lore line and unlock cost."""
    out = [HEADER, f"package {PACKAGE}.pathway;", "",
           "import java.util.List;", "import java.util.Map;", "",
           "/**",
           " * All pathway / sequence definitions. The Fool pathway is implemented to Sequence 0;",
           " * the other seven are registered with their sequence ladders and potions so they can be",
           " * developed without touching the registry.",
           " */",
           "public final class PathwayData {",
           "    private PathwayData() {}",
           "",
           "    /** One sequence: its index (9 = weakest, 0 = strongest), name, lore and abilities. */",
           "    public record SequenceDef(int sequence, String id, String name, String lore,",
           "                              List<String> abilities, String potionId) {}",
           "",
           "    /** One pathway: identity, colour language, lore and the ten sequences. */",
           "    public record PathwayDef(String id, String displayName, int colour, int accent,",
           "                             String emblem, int deepestImplemented, String lore,",
           "                             List<SequenceDef> sequences) {",
           "        public SequenceDef bySequence(int seq) {",
           "            for (SequenceDef s : sequences) {",
           "                if (s.sequence() == seq) return s;",
           "            }",
           "            return null;",
           "        }",
           "        public int maxSequence() { return deepestImplemented; }",
           "    }",
           "",
           "    // ---- ability ids per sequence (implemented in Abilities.java) ----",
           "    private static final Map<String, List<String>> FOOL_ABILITIES = Map.ofEntries(",
           "            Map.entry(\"seer\", List.of(\"supernatural_sight\", \"ore_sense\", \"danger_premonition\", \"perception\")),",
           "            Map.entry(\"clown\", List.of(\"unnatural_agility\", \"fold_step\", \"dodge_instinct\", \"combat_prediction\")),",
           "            Map.entry(\"magician\", List.of(\"stage_illusion\", \"blink\", \"decoy_double\", \"perception_rewrite\")),",
           "            Map.entry(\"faceless\", List.of(\"wear_face\", \"borrowed_mien\", \"feature_shift\", \"mask_of_nobody\")),",
           "            Map.entry(\"marionettist\", List.of(\"soul_thread_view\", \"bind_puppet\", \"puppet_command\", \"sever_thread\")),",
           "            Map.entry(\"bizarro_sorcerer\", List.of(\"bizarro_copy\", \"reality_warp\", \"twisted_mirage\", \"argument_of_copies\")),",
           "            Map.entry(\"scholar_of_yore\", List.of(\"read_the_stone\", \"memory_echo_runtime\", \"echo_summon\", \"rewind_moment\")),",
           "            Map.entry(\"miracle_invoker\", List.of(\"small_miracle\", \"wish_lantern\", \"rainstorm_of_quiet\", \"debt_of_miracles\")),",
           "            Map.entry(\"attendant_of_mysteries\", List.of(\"forbidden_ward\", \"deep_ritual\", \"astral_walk\", \"authority_to_forbid\")),",
           "            Map.entry(\"the_fool\", List.of(\"between_two_truths\", \"unreality_walk\", \"the_space_between\", \"the_noticing_dawn\"))",
           "    );",
           "",
           "    /** Abilities for pathways that are not yet implemented: registered but inert. */",
           "    private static final List<String> PLACEHOLDER = List.of();",
           "",
           ]
    pathway_blocks = []
    for p in PATHWAYS:
        seq_lines = []
        for idx, (sid, sname, lore) in enumerate(p["sequences"]):
            seq_num = 9 - idx
            potion = next((x[0] for x in POTIONS if x[2] == p["id"] and x[3] == seq_num), None)
            quote = chr(34)
            potion_lit = (quote + potion + quote) if potion else "null"
            lore_esc = lore.replace(chr(34), chr(92) + chr(34))
            # no trailing comma: Java does not allow one in an argument list
            seq_lines.append(
                f'                new SequenceDef({seq_num}, "{sid}", '
                f'"{sname}", "{lore_esc}", ABILITIES_{p["id"].upper()}.get("{sid}"), '
                f'{potion_lit})')
        block = [f'            // ---- {p["name"]} ----',
                 '            new PathwayDef(',
                 f'                    "{p["id"]}", "{p["name"]}", '
                 f'{p["color"].replace("#", "0xFF")}, {p["accent"].replace("#", "0xFF")},',
                 f'                    "{p["emblem"]}", {p["implemented"]},',
                 f'                    "{p["lore"].replace(chr(34), chr(92) + chr(34))}",',
                 '                    List.of(']
        block.append(",\n".join(seq_lines))
        block.append('                    ))')
        pathway_blocks.append("\n".join(block))
    out.append("    public static final List<PathwayDef> ALL = List.of(")
    out.append(",\n".join(pathway_blocks))
    out += ["    );",
            "",
            "    public static PathwayDef byId(String id) {",
            "        for (PathwayDef p : ALL) {",
            "            if (p.id().equals(id)) return p;",
            "        }",
            "        return ALL.get(0);",
            "    }",
            "",
            "    public static PathwayDef byIndex(int index) {",
            "        return ALL.get(Math.max(0, Math.min(ALL.size() - 1, index)));",
            "    }",
            "}",
            ""]
    # placeholder ability maps for the other pathways so the emitted code compiles
    body = "\n".join(out)
    placeholders = []
    for p in PATHWAYS:
        if p["id"] == "fool":
            continue
        entries = ", ".join(f'"{s[0]}"' for s in p["sequences"])
        placeholders.append(f"    private static final Map<String, List<String>> ABILITIES_{p['id'].upper()} = "
                            f"Map.ofEntries({', '.join(f'Map.entry({e}, PLACEHOLDER)' for e in entries.split(', '))});")
    # insert placeholder maps before ALL
    marker = "    public static final List<PathwayDef> ALL = List.of("
    body = body.replace(marker, "\n".join(placeholders) + "\n\n" + marker)
    # ABILITIES_FOOL alias
    body = body.replace("FOOL_ABILITIES", "ABILITIES_FOOL")
    w("pathway/PathwayData.java", body)


def gen_sounds():
    out = [HEADER, f"package {PACKAGE}.registry;", "",
           "import net.minecraft.core.registries.Registries;",
           "import net.minecraft.resources.ResourceLocation;",
           "import net.minecraft.sounds.SoundEvent;",
           "import net.neoforged.neoforge.registries.DeferredHolder;",
           "import net.neoforged.neoforge.registries.DeferredRegister;",
           "",
           f'import static {PACKAGE}.PathwaysMod.MOD_ID;',
           "",
           "/** Every sound in the mod. Files live in assets/" + MOD_ID + "/sounds/*.ogg (procedurally synthesized). */",
           "public final class ModSounds {",
           "    private ModSounds() {}",
           "",
           "    public static final DeferredRegister<SoundEvent> SOUNDS =",
           "            DeferredRegister.create(Registries.SOUND_EVENT, MOD_ID);",
           ""]
    for name, _cat, desc in SOUNDS:
        const = "".join(part.capitalize() for part in name.split("_"))
        out.append(f'    /** {desc} */')
        out.append(f'    public static final DeferredHolder<SoundEvent, SoundEvent> {const} = register("{name}");')
    out += ["",
            "    private static DeferredHolder<SoundEvent, SoundEvent> register(String name) {",
            "        ResourceLocation id = ResourceLocation.fromNamespaceAndPath(MOD_ID, name);",
            "        return SOUNDS.register(name, () -> SoundEvent.createVariableRangeEvent(id));",
            "    }",
            "",
            "    public static void register(net.neoforged.bus.api.IEventBus bus) {",
            "        SOUNDS.register(bus);",
            "    }",
            "}",
            ""]
    w("registry/ModSounds.java", "\n".join(out))


def gen_effects():
    out = [HEADER, f"package {PACKAGE}.registry;", "",
           "import net.minecraft.core.registries.Registries;",
           "import net.minecraft.world.effect.MobEffect;",
           "import net.neoforged.neoforge.registries.DeferredHolder;",
           "import net.neoforged.neoforge.registries.DeferredRegister;",
           "",
           f'import static {PACKAGE}.PathwaysMod.MOD_ID;',
           f'import {PACKAGE}.effect.OccultEffects;',
           "",
           "/** Mob effects. Behaviour lives in effect/OccultEffects. */",
           "public final class ModEffects {",
           "    private ModEffects() {}",
           "",
           "    public static final DeferredRegister<MobEffect> EFFECTS =",
           "            DeferredRegister.create(Registries.MOB_EFFECT, MOD_ID);",
           ""]
    for eid, name, kind, desc in EFFECTS:
        const = "".join(part.capitalize() for part in eid.split("_"))
        out.append(f'    /** {name} - {desc} */')
        out.append(f'    public static final DeferredHolder<MobEffect, MobEffect> {const} =')
        out.append(f'            EFFECTS.register("{eid}", () -> OccultEffects.create("{eid}"));')
    out += ["",
            "    public static void register(net.neoforged.bus.api.IEventBus bus) {",
            "        EFFECTS.register(bus);",
            "    }",
            "}",
            ""]
    w("registry/ModEffects.java", "\n".join(out))


def gen_particles():
    out = [HEADER, f"package {PACKAGE}.registry;", "",
           "import net.minecraft.core.particles.ParticleType;",
           "import net.minecraft.core.particles.SimpleParticleType;",
           "import net.minecraft.core.registries.Registries;",
           "import net.neoforged.neoforge.registries.DeferredHolder;",
           "import net.neoforged.neoforge.registries.DeferredRegister;",
           "",
           f'import static {PACKAGE}.PathwaysMod.MOD_ID;',
           "",
           "/** Custom particles: spirit motes, rune dust, black wisps, impossible shards. */",
           "public final class ModParticles {",
           "    private ModParticles() {}",
           "",
           "    public static final DeferredRegister<ParticleType<?>> PARTICLES =",
           "            DeferredRegister.create(Registries.PARTICLE_TYPE, MOD_ID);",
           ""]
    for pid, desc in PARTICLES:
        const = "".join(part.capitalize() for part in pid.split("_"))
        out.append(f'    /** {desc} */')
        out.append(f'    public static final DeferredHolder<ParticleType<?>, SimpleParticleType> {const} =')
        out.append(f'            PARTICLES.register("{pid}", () -> new SimpleParticleType(false));')
    out += ["",
            "    public static void register(net.neoforged.bus.api.IEventBus bus) {",
            "        PARTICLES.register(bus);",
            "    }",
            "}",
            ""]
    w("registry/ModParticles.java", "\n".join(out))


def gen_blocks():
    out = [HEADER, f"package {PACKAGE}.registry;", "",
           "import net.minecraft.core.registries.Registries;",
           "import net.minecraft.world.item.BlockItem;",
           "import net.minecraft.world.item.Item;",
           "import net.minecraft.world.level.block.Block;",
           "import net.minecraft.world.level.block.SlabBlock;",
           "import net.minecraft.world.level.block.SoundType;",
           "import net.minecraft.world.level.block.StairBlock;",
           "import net.minecraft.world.level.block.WallBlock;",
           "import net.minecraft.world.level.block.state.BlockBehaviour;",
           "import net.minecraft.world.level.material.MapColor;",
           "import net.minecraft.world.level.material.PushReaction;",
           "import net.neoforged.neoforge.registries.DeferredBlock;",
           "import net.neoforged.neoforge.registries.DeferredHolder;",
           "import net.neoforged.neoforge.registries.DeferredRegister;",
           "import net.neoforged.neoforge.registries.DeferredItem;",
           "",
           "import java.util.function.Supplier;",
           "",
           f'import static {PACKAGE}.PathwaysMod.MOD_ID;',
           f'import {PACKAGE}.block.OccultBlocks;',
           "",
           "/** Every block plus its BlockItem. Properties are data-driven from tools/content.py. */",
           "public final class ModBlocks {",
           "    private ModBlocks() {}",
           "",
           "    public static final DeferredRegister.Blocks BLOCKS = DeferredRegister.createBlocks(MOD_ID);",
           "    public static final DeferredRegister.Items BLOCK_ITEMS = DeferredRegister.createItems(MOD_ID);",
           ""]
    for bid, kind in BLOCKS:
        hardness, resist, light, sound, tool, needs_tool = BLOCK_SPECS[bid]
        cls, _ = BLOCK_CLASSES.get(bid, ("SimpleBlockFactory", kind))
        const = "".join(part.capitalize() for part in bid.split("_"))
        out.append(f'    /** {bid} */')
        out.append(f'    public static final DeferredBlock<Block> {const} = BLOCKS.register("{bid}",')
        out.append(f'            () -> OccultBlocks.SimpleBlockFactory.create("{bid}", {hardness}f, {resist}f, {light}, '
                   f'"{sound}", {java_bool(needs_tool)}));')
        out.append(f'    public static final DeferredItem<BlockItem> {const}_ITEM =')
        out.append(f'            BLOCK_ITEMS.registerSimpleBlockItem("{bid}", {const});')
        out.append("")
    out += ["    public static void register(net.neoforged.bus.api.IEventBus bus) {",
            "        BLOCKS.register(bus);",
            "        BLOCK_ITEMS.register(bus);",
            "    }",
            "}",
            ""]
    w("registry/ModBlocks.java", "\n".join(out))


def gen_items():
    out = [HEADER, f"package {PACKAGE}.registry;", "",
           "import net.minecraft.world.item.Item;",
           "import net.minecraft.world.item.Rarity;",
           "import net.neoforged.neoforge.registries.DeferredItem;",
           "import net.neoforged.neoforge.registries.DeferredRegister;",
           "",
           f'import static {PACKAGE}.PathwaysMod.MOD_ID;',
           f'import {PACKAGE}.item.OccultItems;',
           "",
           "/** Every item: pathway potions, ingredients, sealed artifacts, occult tools. */",
           "public final class ModItems {",
           "    private ModItems() {}",
           "",
           "    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(MOD_ID);",
           ""]
    out.append("    // ---- pathway potions ----")
    for pid, name, pathway, seq, colour, glow, rarity in POTIONS:
        const = "".join(part.capitalize() for part in pid.split("_"))
        out.append(f'    /** {name} - {pathway} Sequence {seq} */')
        out.append(f'    public static final DeferredItem<Item> {const} = ITEMS.register("{pid}",')
        out.append(f'            () -> new OccultItems.PathwayPotionItem(new Item.Properties().stacksTo(4), '
                   f'"{pathway.lower()}", {seq}, 0x{colour.lstrip("#")}, "{glow}"));')
    out.append("")
    out.append("    // ---- supernatural ingredients ----")
    for iid, name, tier, origin, lore in INGREDIENTS:
        const = "".join(part.capitalize() for part in iid.split("_"))
        out.append(f'    /** {name} - {origin} */')
        out.append(f'    public static final DeferredItem<Item> {const} = ITEMS.register("{iid}",')
        out.append(f'            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), {tier}));')
    out.append("")
    out.append("    // ---- sealed artifacts ----")
    for aid, name, rarity, desc, passive, drawback in ARTIFACTS:
        const = "".join(part.capitalize() for part in aid.split("_"))
        cls = ITEM_CLASSES[aid]
        out.append(f'    /** {name} - {desc} */')
        out.append(f'    public static final DeferredItem<Item> {const} = ITEMS.register("{aid}",')
        out.append(f'            () -> new OccultItems.{cls}(new Item.Properties().stacksTo(1)'
                   f'.rarity(Rarity.{rarity_name(rarity)})));')
    out.append("")
    out.append("    // ---- occult tools ----")
    for uid, name, desc in UTILITY_ITEMS:
        const = "".join(part.capitalize() for part in uid.split("_"))
        cls = ITEM_CLASSES[uid]
        out.append(f'    /** {name} - {desc} */')
        out.append(f'    public static final DeferredItem<Item> {const} = ITEMS.register("{uid}",')
        out.append(f'            () -> new OccultItems.{cls}(new Item.Properties().stacksTo(1)));')
    out.append("")
    out.append("    // ---- drops ----")
    out.append('    public static final DeferredItem<Item> CORRUPTED_HEART_DROP = ITEMS.register("corrupted_heart",')
    out.append("            () -> new OccultItems.SimpleLoreItem(new Item.Properties(), 4));")
    out += ["",
            "    private static String rarityName(int tier) {",
            "        return switch (tier) {",
            '            case 2 -> "UNCOMMON";',
            '            case 3 -> "RARE";',
            '            case 4, 5 -> "EPIC";',
            '            default -> "COMMON";',
            "        };",
            "    }",
            "",
            "    public static void register(net.neoforged.bus.api.IEventBus bus) {",
            "        ITEMS.register(bus);",
            "    }",
            "}",
            ""]
    w("registry/ModItems.java", "\n".join(out))


def rarity_name(tier):
    return {1: "COMMON", 2: "UNCOMMON", 3: "RARE", 4: "EPIC", 5: "EPIC"}.get(tier, "COMMON")


def gen_entities():
    out = [HEADER, f"package {PACKAGE}.registry;", "",
           "import net.minecraft.core.registries.Registries;",
           "import net.minecraft.world.entity.EntityType;",
           "import net.minecraft.world.entity.MobCategory;",
           "import net.neoforged.neoforge.registries.DeferredHolder;",
           "import net.neoforged.neoforge.registries.DeferredRegister;",
           "",
           f'import static {PACKAGE}.PathwaysMod.MOD_ID;',
           f'import {PACKAGE}.entity.OccultEntities;',
           f'import {PACKAGE}.entity.boss.ChoirmasterEntity;',
           f'import {PACKAGE}.entity.boss.UnblinkingEntity;',
           "",
           "/** Every supernatural creature and boss. Attributes are registered in EntityEvents. */",
           "public final class ModEntities {",
           "    private ModEntities() {}",
           "",
           "    public static final DeferredRegister<EntityType<?>> ENTITIES =",
           "            DeferredRegister.create(Registries.ENTITY_TYPE, MOD_ID);",
           ""]
    for eid, _cat, _beh, _threat, _sanity in REGULAR_ENTITIES + SUMMONED_ENTITIES + BOSSES:
        cls, category, width, height = ENTITY_CLASSES[eid]
        const = "".join(part.capitalize() for part in eid.split("_"))
        factory = {
            "ChoirmasterEntity": "ChoirmasterEntity::new",
            "UnblinkingEntity": "UnblinkingEntity::new",
        }.get(cls, f"OccultEntities.{cls}::new")
        out.append(f'    /** {eid} */')
        holder = "OccultEntities." + cls if cls not in ("ChoirmasterEntity", "UnblinkingEntity") else cls
        out.append(f'    public static final DeferredHolder<EntityType<?>, EntityType<{holder}>> {const} =')
        out.append(f'            ENTITIES.register("{eid}", () -> EntityType.Builder.of({factory}, MobCategory.{category})')
        out.append(f'                    .sized({width}f, {height}f)')
        out.append(f'                    .clientTrackingRange(10)')
        out.append(f'                    .build("{eid}"));')
        out.append("")
    out += ["    public static void register(net.neoforged.bus.api.IEventBus bus) {",
            "        ENTITIES.register(bus);",
            "    }",
            "}",
            ""]
    w("registry/ModEntities.java", "\n".join(out))



TAB_ARTIFACT_TOOLS = ("thread_shears", "soul_thread_spool", "occult_compass", "ward_charm", "spirit_tonic")
TAB_BEYOND_KEYS = ("void", "beyond", "starless", "memory", "corrupted", "abyss")


def gen_tab_contents():
    """Tab contents are emitted as id lists: a pack that disables an entry simply skips it."""
    potions = [p[0] for p in POTIONS]
    ingredients = [i[0] for i in INGREDIENTS]
    artifacts = [a[0] for a in ARTIFACTS]
    utility = [u[0] for u in UTILITY_ITEMS]
    blocks = [b[0] for b in BLOCKS]

    beyond = [i for i in blocks + ingredients + utility
              if any(key in i for key in TAB_BEYOND_KEYS)]
    artifacts_tab = list(artifacts) + [t for t in TAB_ARTIFACT_TOOLS if t in utility]
    ritual = ([b for b in blocks if b not in beyond]
              + [i for i in ingredients if i not in beyond]
              + [u for u in utility if u not in artifacts_tab
                 and u not in beyond and u != "pathway_codex"])
    paths = list(potions) + ["pathway_codex"]

    out = [HEADER, f"package {PACKAGE}.registry;", "",
           "import java.util.List;",
           "import java.util.Map;",
           "",
           "import net.minecraft.core.registries.BuiltInRegistries;",
           "import net.minecraft.resources.ResourceLocation;",
           "import net.minecraft.world.item.CreativeModeTab;",
           "import net.minecraft.world.item.Item;",
           "import net.minecraft.world.item.Items;",
           "",
           f'import static {PACKAGE}.PathwaysMod.MOD_ID;',
           "",
           "/** Curated creative-tab contents: each tab reads as a set, not a pile. */",
           "public final class TabContents {",
           "    private TabContents() {}",
           "",
           "    private static final Map<String, List<String>> BY_TAB = Map.of("]
    listings = [("pathways", paths), ("pathway_ritual", ritual),
                ("pathway_artifacts", artifacts_tab), ("pathway_beyond", beyond)]
    for index, (tab, ids) in enumerate(listings):
        out.append(f'            "{tab}", List.of(')
        for j, iid in enumerate(ids):
            comma = "," if j < len(ids) - 1 else ""
            out.append(f'                    "{iid}"{comma}')
        out.append(f'            ){"," if index < len(listings) - 1 else ""}')
    out += ["    );",
            "",
            "    /** Adds one tab's entries; ids that are missing from the registry are skipped. */",
            "    public static void fill(String tab, CreativeModeTab.Output output) {",
            "        for (String id : BY_TAB.getOrDefault(tab, List.of())) {",
            "            Item item = BuiltInRegistries.ITEM.get(ResourceLocation.fromNamespaceAndPath(MOD_ID, id));",
            "            if (item != Items.AIR) {",
            "                output.accept(item);",
            "            }",
            "        }",
            "    }",
            "}",
            ""]
    w("registry/TabContents.java", "\n".join(out))


def gen_tabs():
    out = [HEADER, f"package {PACKAGE}.registry;", "",
           "import net.minecraft.core.registries.Registries;",
           "import net.minecraft.network.chat.Component;",
           "import net.minecraft.world.item.CreativeModeTab;",
           "import net.minecraft.world.item.ItemStack;",
           "import net.neoforged.neoforge.registries.DeferredHolder;",
           "import net.neoforged.neoforge.registries.DeferredRegister;",
           "",
           f'import static {PACKAGE}.PathwaysMod.MOD_ID;',
           "",
           "/** Four creative tabs: the whole mod reads as one curated expansion, not a dump. */",
           "public final class ModTabs {",
           "    private ModTabs() {}",
           "",
           "    public static final DeferredRegister<CreativeModeTab> TABS =",
           "            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, MOD_ID);",
           ""]
    for tid, tname, ticon in TABS:
        const = "".join(part.capitalize() for part in tid.split("_"))
        out.append(f'    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> {const} =')
        out.append(f'            TABS.register("{tid}", () -> CreativeModeTab.builder()')
        out.append(f'                    .title(Component.translatable("itemGroup.{MOD_ID}.{tid}"))')
        out.append(f'                    .icon(() -> icon("{ticon}"))')
        out.append(f'                    .displayItems((params, output) -> TabContents.fill("{tid}", output))')
        out.append("                    .build());")
        out.append("")
    out += ["    /** Lazy icon lookup: tab icons are evaluated after every registry is populated. */",
            "    private static ItemStack icon(String id) {",
            "        return new ItemStack(net.minecraft.core.registries.BuiltInRegistries.ITEM.get(",
            "                net.minecraft.resources.ResourceLocation.fromNamespaceAndPath(MOD_ID, id)));",
            "    }",
            "",
            "    public static void register(net.neoforged.bus.api.IEventBus bus) {",
            "        TABS.register(bus);",
            "    }",
            "}",
            ""]
    w("registry/ModTabs.java", "\n".join(out))


VI_SUBTITLES = {
    "potion_drink": "Tiếng nuốt thuốc", "potion_brew": "Tiếng thuốc sủi bọt",
    "potion_finish": "Nút chai mở ra", "codex_open": "Mở sách da",
    "codex_page": "Lật trang giấy", "bell_ring": "Chuông đồng rỉ",
    "bell_answer": "Có tiếng đáp lại", "artifact_activate": "Cổ vật khởi động",
    "artifact_curse": "Lời nguyền của cổ vật", "thread_bind": "Sợi chỉ kết nối",
    "thread_sever": "Sợi chỉ đứt", "thread_tension": "Sợi chỉ căng",
    "chalk_draw": "Vẽ vòng phấn", "dagger_cut": "Dao nghi lễ rạch",
    "ritual_start": "Nghi lễ bắt đầu", "ritual_loop": "Vòng tròn nghi lễ",
    "ritual_pulse": "Nhịp nghi lễ", "ritual_chant": "Tiếng tụng niệm",
    "ritual_complete": "Nghi lễ hoàn tất", "ritual_fail": "Nghi lễ thất bại",
    "whisper_near": "Lời thì thầm gần", "whisper_far": "Lời thì thầm xa",
    "heartbeat": "Nhịp tim", "breathing": "Tiếng thở", "knock": "Tiếng gõ cửa",
    "rumble": "Tiếng rung sâu", "static": "Tiếng nhiễu",
    "watcher_stare": "Kẻ Quan Sát nhìn", "watcher_vanish": "Kẻ Quan Sát biến mất",
    "hollow_step": "Bước chân rỗng", "hollow_idle": "Hơi thở rỗng",
    "husk_whisper": "Xác Thì Thầm", "husk_attack": "Xác Thì Thầm tấn công",
    "marionette_joint": "Khớp rối gỗ", "choirmaster_chant": "Chủ Lễ tụng niệm",
    "choirmaster_scream": "Chủ Lễ gào thét", "unblinking_gaze": "Cái Nhìn Không Chớp",
    "unblinking_hurt": "Cái Nhìn bị thương", "unblinking_death": "Cái Nhìn tắt",
    "tenant_possess": "Kẻ Trú Ngụ chiếm xác", "sequence_advance": "Thăng tiến Bậc",
    "sequence_digest": "Tiêu hoá dược tính", "corruption_pulse": "Mạch Ô Nhiễm",
    "spirit_enter": "Bước vào Thế Giới Linh", "spirit_exit": "Trở về xác thân",
    "spirit_ambient": "Âm thanh Thế Giới Linh", "spirit_strain": "Dây neo căng",
    "spirit_snap": "Dây neo đứt", "red_moon": "Trăng Máu",
    "veil_thins": "Màn Che Mỏng Đi", "whispering_night": "Đêm Thì Thầm",
    "memory_echo": "Vọng Ký Ức", "faceless_shift": "Khuôn mặt đổi hình",
    "authority_forbid": "Mệnh lệnh Cấm", "beyond_call": "Tiếng gọi từ Bên Kia",
    "beyond_arrival": "Bên Kia hiện diện",
}


def gen_lang():
    """en_us.json + vi_vn.json: real names, lore, GUI strings, subtitles."""
    en = {
        "itemGroup.pathwaysofthebeyond.pathways": "Pathways of the Beyond",
        "itemGroup.pathwaysofthebeyond.pathway_ritual": "Occult Ritual",
        "itemGroup.pathwaysofthebeyond.pathway_artifacts": "Sealed Artifacts",
        "itemGroup.pathwaysofthebeyond.pathway_beyond": "The Beyond",
        # HUD / screens
        "gui.pathwaysofthebeyond.sanity": "Sanity",
        "gui.pathwaysofthebeyond.corruption": "Corruption",
        "gui.pathwaysofthebeyond.digestion": "Digestion",
        "gui.pathwaysofthebeyond.sequence": "Sequence",
        "gui.pathwaysofthebeyond.pathway": "Pathway",
        "gui.pathwaysofthebeyond.next": "Next",
        "gui.pathwaysofthebeyond.abilities": "Abilities",
        "gui.pathwaysofthebeyond.requirements": "Advancement Requirements",
        "gui.pathwaysofthebeyond.lore": "Lore",
        "gui.pathwaysofthebeyond.stability": "Stability",
        "gui.pathwaysofthebeyond.danger": "Danger",
        "gui.pathwaysofthebeyond.ingredients": "Required Components",
        "gui.pathwaysofthebeyond.begin": "Begin Ritual",
        "gui.pathwaysofthebeyond.abort": "Break the Circle",
        "gui.pathwaysofthebeyond.close": "Close",
        "gui.pathwaysofthebeyond.codex": "Codex of Forbidden Knowledge",
        "gui.pathwaysofthebeyond.no_pathway": "No pathway. You are still only a person.",
        "gui.pathwaysofthebeyond.digesting": "Digesting: %s%%",
        "gui.pathwaysofthebeyond.ready": "Ready to advance",
        # messages
        "message.pathwaysofthebeyond.potion_consumed": "The potion takes hold. Your body begins its argument with it.",
        "message.pathwaysofthebeyond.digesting_hold": "You cannot drink another pathway potion while digesting.",
        "message.pathwaysofthebeyond.advanced": "Sequence %s: %s",
        "message.pathwaysofthebeyond.digestion_regressed": "Something in you rejects the pathway.",
        "message.pathwaysofthebeyond.lost_control": "You are no longer the one walking.",
        "message.pathwaysofthebeyond.ritual_started": "The circle is open. Do not step outside it.",
        "message.pathwaysofthebeyond.ritual_failed": "The circle breaks. Something noticed the attempt.",
        "message.pathwaysofthebeyond.ritual_complete": "The ritual closes cleanly. The air tastes of brass.",
        "message.pathwaysofthebeyond.insufficient_sequence": "You are not far enough along the pathway for this.",
        "message.pathwaysofthebeyond.soul_exit": "Your body remains behind. Do not stray far.",
        "message.pathwaysofthebeyond.soul_return": "You fall back into yourself.",
        "message.pathwaysofthebeyond.soul_snap": "The tether parts. Something is standing over your body.",
        "message.pathwaysofthebeyond.thread_bound": "The thread takes hold.",
        "message.pathwaysofthebeyond.thread_severed": "The thread is cut.",
        "message.pathwaysofthebeyond.bell_answered": "Something answers the bell. It is not close, yet.",
        "message.pathwaysofthebeyond.event_red_moon": "The moon has turned the colour of an old wound.",
        "message.pathwaysofthebeyond.event_whispering_night": "Everything is whispering, and none of it is aimed at you.",
        "message.pathwaysofthebeyond.event_veil_thins": "The Veil is thin tonight.",
        "message.pathwaysofthebeyond.event_the_watcher": "You are being watched. It has not decided anything yet.",
        "message.pathwaysofthebeyond.event_memory_echo": "This place remembers happening.",
        "message.pathwaysofthebeyond.event_empty_village": "The village is quiet in the wrong way.",
        "message.pathwaysofthebeyond.event_the_noticing": "Something very large has become aware of you.",
        "message.pathwaysofthebeyond.spirit_enter": "The world drains of colour.",
        "message.pathwaysofthebeyond.spirit_exit": "Colour returns, too quickly.",
        "message.pathwaysofthebeyond.beyond_unlocked": "THE BEYOND has noticed you.",
        # effects
        "effect.pathwaysofthebeyond.lost_control": "Lost Control",
        # entities
        "entity.pathwaysofthebeyond.choirmaster_of_the_veil": "The Choirmaster of the Veil",
        "entity.pathwaysofthebeyond.the_unblinking": "The Unblinking",
        "entity.pathwaysofthebeyond.marionette": "Marionette",
        "entity.pathwaysofthebeyond.bizarro_clone": "Bizarro Double",
        "entity.pathwaysofthebeyond.historical_echo": "Historical Echo",
        "entity.pathwaysofthebeyond.player_body": "Your Body",
        # commands
        "commands.pathwaysofthebeyond.pathway.none": "No pathway set.",
        "commands.pathwaysofthebeyond.set": "Set %s to %s.",
        "commands.pathwaysofthebeyond.reset": "Occult data cleared for %s.",
    }
    for pid, name, pathway, seq, colour, glow, rarity in POTIONS:
        en[f"item.pathwaysofthebeyond.{pid}"] = f"{name} Potion"
    for iid, name, tier, origin, lore in INGREDIENTS:
        en[f"item.pathwaysofthebeyond.{iid}"] = name
        en[f"item.pathwaysofthebeyond.{iid}.lore"] = lore
    for aid, name, rarity, desc, passive, drawback in ARTIFACTS:
        en[f"item.pathwaysofthebeyond.{aid}"] = name
        en[f"item.pathwaysofthebeyond.{aid}.desc"] = desc
        en[f"item.pathwaysofthebeyond.{aid}.passive"] = passive
        en[f"item.pathwaysofthebeyond.{aid}.drawback"] = drawback
    for uid, name, desc in UTILITY_ITEMS:
        en[f"item.pathwaysofthebeyond.{uid}"] = name
        en[f"item.pathwaysofthebeyond.{uid}.desc"] = desc
    en["item.pathwaysofthebeyond.corrupted_heart"] = "Corrupted Heart"
    names = {
        "ritual_altar": "Occult Ritual Altar", "ritual_pedestal": "Ritual Pedestal",
        "ritual_candle": "Ritual Candle", "chalk_circle": "Chalk Circle",
        "occult_table": "Occult Work Table", "blood_basin": "Blood Basin",
        "spirit_lantern": "Spirit Lantern", "occult_archive": "Occult Archive",
        "gothic_bricks": "Gothic Bricks", "gothic_brick_stairs": "Gothic Brick Stairs",
        "gothic_brick_slab": "Gothic Brick Slab", "gothic_brick_wall": "Gothic Brick Wall",
        "desecrated_stone": "Desecrated Stone", "desecrated_stone_stairs": "Desecrated Stone Stairs",
        "desecrated_stone_slab": "Desecrated Stone Slab", "weathered_plaster": "Weathered Plaster",
        "dark_planks": "Dark Planks", "dark_plank_stairs": "Dark Plank Stairs",
        "dark_plank_slab": "Dark Plank Slab", "iron_grate": "Iron Grate",
        "slate_tiles": "Slate Tiles", "slate_tile_stairs": "Slate Tile Stairs",
        "slate_tile_slab": "Slate Tile Slab", "veil_glass": "Veil Glass",
        "void_stone": "Void Stone", "spirit_flower": "Spirit Flower",
        "moonlit_fungus": "Moonlit Fungus", "memory_shard_block": "Memory Shard Block",
    }
    for bid, _kind in BLOCKS:
        en[f"block.pathwaysofthebeyond.{bid}"] = names[bid]
    subtitles = {
        "bell_answer": "Something answers", "thread_snap": "A thread parts",
    }
    for name, _cat, desc in SOUNDS:
        en[f"subtitles.pathwaysofthebeyond.{name}"] = desc
    for eid, name, kind, desc in EFFECTS:
        en[f"effect.pathwaysofthebeyond.{eid}"] = name
    for (sid, sname, lore) in PATHWAYS[0]["sequences"]:
        en[f"sequence.pathwaysofthebeyond.{sid}"] = sname
    for p in PATHWAYS:
        en[f"pathway.pathwaysofthebeyond.{p['id']}"] = p["name"]
        en[f"pathway.pathwaysofthebeyond.{p['id']}.lore"] = p["lore"]
    for st in SANITY_TIERS:
        en[f"sanity.pathwaysofthebeyond.{st[0]}"] = st[1]
    for cs in CORRUPTION_STAGES:
        en[f"corruption.pathwaysofthebeyond.{cs[0]}"] = cs[1]

    vi = dict(en)
    vi.update({
        "itemGroup.pathwaysofthebeyond.pathways": "Con Đường Bên Kia",
        "itemGroup.pathwaysofthebeyond.pathway_ritual": "Nghi Lễ Huyền Bí",
        "itemGroup.pathwaysofthebeyond.pathway_artifacts": "Cổ Vật Phong Ấn",
        "itemGroup.pathwaysofthebeyond.pathway_beyond": "Bên Kia",
        "gui.pathwaysofthebeyond.sanity": "Tỉnh Táo",
        "gui.pathwaysofthebeyond.corruption": "Ô Nhiễm",
        "gui.pathwaysofthebeyond.digestion": "Tiêu Hoá",
        "gui.pathwaysofthebeyond.sequence": "Bậc",
        "gui.pathwaysofthebeyond.pathway": "Con Đường",
        "gui.pathwaysofthebeyond.stability": "Ổn Định",
        "gui.pathwaysofthebeyond.begin": "Bắt Đầu Nghi Lễ",
        "gui.pathwaysofthebeyond.no_pathway": "Chưa có con đường. Ngươi vẫn chỉ là người.",
        "message.pathwaysofthebeyond.potion_consumed": "Dược tính ngấm vào. Cơ thể ngươi bắt đầu phản đối.",
        "message.pathwaysofthebeyond.digesting_hold": "Ngươi không thể uống thêm khi đang tiêu hoá.",
        "message.pathwaysofthebeyond.advanced": "Bậc %s: %s",
        "message.pathwaysofthebeyond.lost_control": "Ngươi không còn là kẻ đang bước đi.",
        "message.pathwaysofthebeyond.ritual_started": "Vòng tròn đã mở. Đừng bước ra ngoài.",
        "message.pathwaysofthebeyond.ritual_failed": "Vòng tròn vỡ. Có thứ gì đó đã chú ý.",
        "message.pathwaysofthebeyond.ritual_complete": "Nghi lễ khép lại sạch sẽ. Không khí có mùi đồng thau.",
        "message.pathwaysofthebeyond.soul_exit": "Thân xác ngươi ở lại. Đừng đi quá xa.",
        "message.pathwaysofthebeyond.soul_return": "Ngươi rơi trở lại vào chính mình.",
        "message.pathwaysofthebeyond.beyond_unlocked": "BÊN KIA đã nhận ra ngươi.",
        "effect.pathwaysofthebeyond.lost_control": "Mất Kiểm Soát",
        "entity.pathwaysofthebeyond.choirmaster_of_the_veil": "Chủ Lễ Màn Sương",
        "entity.pathwaysofthebeyond.the_unblinking": "Kẻ Không Chớp Mắt",
    })
    import json
    # subtitles: one per sound event, in both languages
    for _entry in SOUNDS:
        _sid, _desc = _entry[0], _entry[2]
        _en = _desc[:1].upper() + _desc[1:] if _desc else _sid.replace("_", " ")
        en.setdefault("sound.pathwaysofthebeyond." + _sid, _en)
        vi.setdefault("sound.pathwaysofthebeyond." + _sid,
                      VI_SUBTITLES.get(_sid, _en))
    data_dir = os.path.join(ROOT, "src", "main", "resources", "assets", MOD_ID, "lang")
    os.makedirs(data_dir, exist_ok=True)
    with open(os.path.join(data_dir, "en_us.json"), "w", encoding="utf-8") as f:
        json.dump(en, f, indent=2, ensure_ascii=False, sort_keys=True)
        f.write("\n")
    with open(os.path.join(data_dir, "vi_vn.json"), "w", encoding="utf-8") as f:
        json.dump(vi, f, indent=2, ensure_ascii=False, sort_keys=True)
        f.write("\n")
    print("  wrote assets/%s/lang/en_us.json (%d keys)" % (MOD_ID, len(en)))
    print("  wrote assets/%s/lang/vi_vn.json (%d keys)" % (MOD_ID, len(vi)))
    return en


def gen_sounds_json():
    """Writes assets/pathwaysofthebeyond/sounds.json.

    One entry per registered sound event id. Minecraft resolves sound events by id, so a
    grouped "bank" object silently leaves every SoundEvent unplayable.
    """
    data_dir = os.path.join(ROOT, "src", "main", "resources", "assets", MOD_ID)
    os.makedirs(data_dir, exist_ok=True)
    path = os.path.join(data_dir, "sounds.json")
    payload = {}
    for entry in SOUNDS:
        sound_id = entry[0]
        payload[sound_id] = {
            "subtitle": "sound.pathwaysofthebeyond." + sound_id,
            "sounds": [
                {"name": "pathwaysofthebeyond:" + sound_id, "stream": False}
            ],
        }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print("  wrote sounds.json (%d sound events)" % len(payload))

def main():
    print("[java] generating registries from content.py")
    gen_pathway_data()
    gen_sounds()
    gen_effects()
    gen_particles()
    gen_blocks()
    gen_items()
    gen_entities()
    gen_tabs()
    gen_tab_contents()
    lang = gen_lang()
    gen_sounds_json()
    print("[java] done")


if __name__ == "__main__":
    main()
